### ISSUE TITLE
开启xpack的权限认证后，ansj的api报未授权

### ISSUE THREAD

**Issue by nfjava** [NLPchina/elasticsearch-analysis-ansj#105]
![image](https://user-images.githubusercontent.com/6111534/35560485-904296fa-05e8-11e8-915e-cd420531ffb9.png)
xpack的用户是超级管理员，不知道什么地方阻挡了授权

**Comment by shi-yuan** [comment]
角色配置的有问题？
你可以看看详细的日志，把日志级别调到debug吧：
```
logger.shield.authc: DEBUG
```

**Comment by nfjava** [comment]
![image](https://user-images.githubusercontent.com/6111534/35601448-0dd1ec58-066e-11e8-8287-6bbc125ba627.png)
我用的是超级管理员角色， 要不你加我qq吧 537005818

**Comment by nfjava** [comment]
![image](https://user-images.githubusercontent.com/6111534/35603687-6d515190-0679-11e8-89cf-f42e2531063e.png)
将ansj的action name改为cluster开头的就解决了，感觉是xpack的role权限分为两类cluster和index。 不认识这种ansj类型的

**Comment by shi-yuan** [comment]
好的，谢谢！我这边看看

**Comment by vgtrey** [comment]
您好, 请问5.x的修改方式不一样吗?
5.6.5 修改NAME="indices:admin/ansj/analyze"后抛java.lang.NullPointerException: null
![image](https://user-images.githubusercontent.com/1548829/37459920-9196b67a-2817-11e8-9072-59745c16b90a.png)

**Comment by shi-yuan** [comment]
访问的http://xxx:xxx/_ansj/flush/dic？传参数了吗？

**Comment by vgtrey** [comment]
传了参数也是报这个错, 其他几个接口"/_cat/ansj", "/_cat/ansj/config", "/_ansj/flush/config"也是报这个错...
