### ISSUE TITLE
启用redis后报告字典位置是config目录不是plugin目录

### ISSUE THREAD

**Issue by anythink-wx** [NLPchina/elasticsearch-analysis-ansj#11]
另一个建议默认配置文件的redis地址改为127.0.0.1

**Comment by ansjsun** [comment]
@4onni  是否可以？

**Comment by ansjsun** [comment]
fix by 5f93711c42b7ce6c310c8d98275cb11abc70bea0

**Comment by oczjack** [comment]
为什么我的elasticsearch2.1.1版本的安装上ansj后高亮显示的还是单字拆分的呢？而且怎么没有停用词词库呢？
