### ISSUE TITLE
illegal_argument_exception

### ISSUE THREAD

**Issue by wilderchen** [NLPchina/elasticsearch-analysis-ansj#110]
INDEX MAPPING:
{
  "mappings": {
    "doc": {
      "properties": {
      	"expected_positions": {
          "analyzer": "index_ansj",
          "type": "text"
        }
      }
    }
  }
}

INDEX PAYLOAD:
{"expected_positions": ["区域销售总监;销售经理", "主管;区域销售经理"]}

RESP:
{
    "error": {
        "root_cause": [
            {
                "type": "illegal_argument_exception",
                "reason": "startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=1,endOffset=3,lastStartOffset=9 for field 'expected_positions'"
            }
        ],
        "type": "illegal_argument_exception",
        "reason": "startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=1,endOffset=3,lastStartOffset=9 for field 'expected_positions'"
    },
    "status": 400
}

_ANALYZE:
{
    "tokens": [
        {
            "token": "区域",
            "start_offset": 0,
            "end_offset": 2,
            "type": "n",
            "position": 0
        },
        {
            "token": "销售",
            "start_offset": 2,
            "end_offset": 4,
            "type": "vn",
            "position": 1
        },
        {
            "token": "总监",
            "start_offset": 4,
            "end_offset": 6,
            "type": "n",
            "position": 2
        },
        {
            "token": ";",
            "start_offset": 6,
            "end_offset": 7,
            "type": "w",
            "position": 3
        },
        {
            "token": "销售",
            "start_offset": 7,
            "end_offset": 9,
            "type": "vn",
            "position": 4
        },
        {
            "token": "经理",
            "start_offset": 9,
            "end_offset": 11,
            "type": "n",
            "position": 5
        },
        {
            "token": "主管",
            "start_offset": 1,
            "end_offset": 3,
            "type": "vn",
            "position": 106
        },
        {
            "token": ";",
            "start_offset": 3,
            "end_offset": 4,
            "type": "w",
            "position": 107
        },
        {
            "token": "区域",
            "start_offset": 4,
            "end_offset": 6,
            "type": "n",
            "position": 108
        },
        {
            "token": "销售",
            "start_offset": 6,
            "end_offset": 8,
            "type": "vn",
            "position": 109
        },
        {
            "token": "经理",
            "start_offset": 8,
            "end_offset": 10,
            "type": "n",
            "position": 110
        }
    ]
}

**Comment by shi-yuan** [comment]
[java.lang.IllegalArgumentException: startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards](https://github.com/NLPchina/elasticsearch-analysis-ansj/issues/109)

**Comment by shi-yuan** [comment]
参考https://github.com/NLPchina/ansj_seg/pull/637，升级ansj_lucene_plugin

**Comment by wilderchen** [comment]
谢谢，我试试看。

**Comment by wilderchen** [comment]
fixed

**Comment by hrdxwandg** [comment]
我也遇到了这个问题，麻烦问下怎么升级ansj_lucene_plugin？

**Comment by shi-yuan** [comment]
由于没有发布到Maven仓库，自行打jar包替换ansj_lucene_plugin吧

**Comment by hrdxwandg** [comment]
fixed, thanks
