### ISSUE TITLE
刷新词典报错

### ISSUE THREAD

**Issue by yeyuelong** [NLPchina/elasticsearch-analysis-ansj#111]
1、同义词词典库synonyms.dic配置：白血病     血癌。分词结果：
![image](https://user-images.githubusercontent.com/20420441/38126248-efe8e5e8-3421-11e8-8e50-f04044afd2c1.png)
2、增加一个新的同义词：白细胞。
刷新词典：http://192.168.130.64:9200/_ansj/flush/dic   返回结果：
![image](https://user-images.githubusercontent.com/20420441/38126313-628e5380-3422-11e8-94ad-bc702e5350f4.png)
结果成功，但是报错，且“血癌”的分词结果也还是原来“白血病”、“血癌”两个词，并无新词“白细胞”：
![image](https://user-images.githubusercontent.com/20420441/38126338-82751576-3422-11e8-9629-5f1904b2d201.png)

shiyuan，您好！想问两个使用问题：
1、如何在不重启ES的情况下，更新词典生效？
2、词典更新生效后，以前ES中的旧数据如何生效新的分词？（不使用reindex的话）

使用版本：6.0

**Comment by yeyuelong** [comment]
上两个问题：
1、不重启ES的情况下，可以根据http刷新词典生效，如：
http://127.0.0.1:9200/_ansj/flush/dic?key=synonyms
2、词典更新生效后，旧数据要生效新的分词还是得reindex一遍数据，因为索引库里面是没有新分词的，跟作者讨论后可以有另一种解决方案：
先分词出所有的结果，如：
![image](https://user-images.githubusercontent.com/20420441/38233115-0fa4c0fa-374c-11e8-9e82-287cb4cadb4f.png)


然后根据分词出的这些term进行terms查询，虽然影响性能，但也是一种解决思路

**Comment by yeyuelong** [comment]
改问题可以关闭了

**Comment by leiguorui** [comment]
刷新词典报错, 找不到索引, 是什么原因啊, 我yong用的es 2.5.3

![image](https://user-images.githubusercontent.com/5110678/63151026-06ba8000-c03b-11e9-83af-16de7d4b3e3d.png)
