### ISSUE TITLE
最新的修改，能否编译成release包提供下载

### ISSUE THREAD

**Issue by armyhg** [NLPchina/elasticsearch-analysis-ansj#113]
大神，最新的修改，能否编译成release包提供下载，非常感谢！
想自己编译来着，试了很久，都没成功，需要好多依赖项。。。

**Comment by armyhg** [comment]
试了一整天，终于编译成功了。不过发现问题还是没有解决：在配置文件中按默认的用上自定义词库default.dic，index_ansj分词太细，每个字都分出来了；如果将自定义词库注释掉，又分得特别粗，index_ansj和query_ansj分出来是一样的。麻烦版主帮忙看看，是哪儿出了问题？

**Comment by armyhg** [comment]
谢谢shi-yuan的回复，不过我这儿不用default.dic时，index_ansj和query_ansj分出来完全一样，分词太粗，这个就没法用了。这肯定是哪儿不对了，请您再查看一下可能是哪儿的问题。

**Comment by shi-yuan** [comment]
可以先看看这几个分词方式的区别：https://github.com/NLPchina/ansj_seg/wiki/%E5%88%86%E8%AF%8D%E6%96%B9%E5%BC%8F

**Comment by armyhg** [comment]
ansj我用了几年了，其它分词不一定熟悉，对index_ansj和query_ansj的区别还是比较清楚的，所以才对现在版本禁用default.dic后，index_ansj和query_ansj分词结果完全一致感到疑惑。请shi-yuan亲自试试看，查查是我的原因还是软件的bug。谢谢！

**Comment by shi-yuan** [comment]
[ansj_seg](https://github.com/NLPchina/ansj_seg)升级后导致的吧，这两种分词方式，应该有变动，您可以在ansj_seg里提个issue，讨论一下
