### ISSUE TITLE
没有识别人名

### ISSUE THREAD

**Issue by YangMatt1** [NLPchina/elasticsearch-analysis-ansj#118]
![image](https://user-images.githubusercontent.com/23712225/41074212-80d43c04-6a39-11e8-95a1-2ccacf365242.png)

ansj:
  #默认参数配置
  isNameRecognition: true #开启姓名识别
  isNumRecognition: true #开启数字识别
  isQuantifierRecognition: true #是否数字和量词合并
  isRealName: false; #是否保留真实词语,建议保留false
请问是哪边有问题呢？

**Comment by shi-yuan** [comment]
词典里增加：邓颖超

**Comment by shi-yuan** [comment]
还有一个方案，是添加歧义词典：[ambiguity.dic](https://github.com/NLPchina/ansj_seg/blob/master/library/ambiguity.dic)

**Comment by YangMatt1** [comment]
@shi-yuan ansj分词器是必须添加自定义词典才能识别姓名吗？isNameRecognition这个属性的意义是什么呢？如果在词典中添加了邓颖超，那肯定按邓颖超取识别啊，就和IK分词器一样

**Comment by shi-yuan** [comment]
不是，邓颖超生前，这句分词的话，是有歧义的

**Comment by YangMatt1** [comment]
@shi-yuan 罗毅虎和曹罗伟是高中同学这句话没有歧义也没有识别出来，被分成了罗、毅、虎、和、曹、罗、伟是什么原因呢

**Comment by shi-yuan** [comment]
不会吧，是不是加了词典呢？我本地测dic_ansj，结果是：
```json
{
    "tokens": [
        {
            "token": "罗毅虎",
            "start_offset": 0,
            "end_offset": 3,
            "type": "nr",
            "position": 0
        },
        {
            "token": "和",
            "start_offset": 3,
            "end_offset": 4,
            "type": "c",
            "position": 1
        },
        {
            "token": "曹罗伟",
            "start_offset": 4,
            "end_offset": 7,
            "type": "nr",
            "position": 2
        },
        {
            "token": "是",
            "start_offset": 7,
            "end_offset": 8,
            "type": "v",
            "position": 3
        },
        {
            "token": "高中",
            "start_offset": 8,
            "end_offset": 10,
            "type": "n",
            "position": 4
        },
        {
            "token": "同学",
            "start_offset": 10,
            "end_offset": 12,
            "type": "n",
            "position": 5
        }
    ]
}
```

**Comment by YangMatt1** [comment]
@shi-yuan 我看了下5.3.0版本的ansj.cfg.yml文件里面的默认自定词典配置里面dic: default.dic文件，没有罗毅虎这个分词，而是罗、毅、虎，是这个原因吗？导致没有识别出来人名？

**Comment by shi-yuan** [comment]
我试的是最新的版本6.2.4，你试试不挂载词典，看看分词结果

**Comment by YangMatt1** [comment]
我换了最新的版本6.2.4没有问题，但是5.3.0的话不挂载词典还是不能识别人名，这跟版本有关系吗？5.3.0版本不能识别这两个人名？

**Comment by shi-yuan** [comment]
我试了试5.x版本的，也是没有问题的，和上面结果是一样的呢

**Comment by YangMatt1** [comment]
@shi-yuan 那有点奇怪呢，我本地好像是没识别出来，配置文件里面应该没问题啊,自定义词典也屏蔽掉了
![image](https://user-images.githubusercontent.com/23712225/41265655-f52da65e-6e25-11e8-8165-6fecd77415d0.png)
![image](https://user-images.githubusercontent.com/23712225/41265753-5abffe7c-6e26-11e8-9a50-92e3027a38f6.png)

**Comment by shi-yuan** [comment]
建议升级ansj_seg，或者基于5.x分支打包一个5.3.0版本的插件
