### ISSUE TITLE
如何让词性可以在返回的analyze结果中显示?

### ISSUE THREAD

**Issue by lubaogui** [NLPchina/elasticsearch-analysis-ansj#12]
您好，目前analyze的结果返回:

  }, {
    "token" : "大爷",
    "start_offset" : 55,
    "end_offset" : 57,
    "type" : "word",
    "position" : 32
  }, {
    "token" : "的",
    "start_offset" : 57,
    "end_offset" : 58,
    "type" : "word",
    "position" : 33
  } ]

如何让type或者添加一个字段让返回的信息包含词性信息?

**Comment by lubaogui** [comment]
已解决，需要修改ansj_seg的源代码，修改设置type属性代码即可。对于redis发布新词，使用yum安装得存在问题，会提示词典文件的路径不对。

**Comment by ansjsun** [comment]
？？？？
