### ISSUE TITLE
windows中elasticsearch 6.0.0 无法将ansj设置为默认分词器

### ISSUE THREAD

**Issue by rtygbwwwerr** [NLPchina/elasticsearch-analysis-ansj#120]
按readme的方法，在elasticsearch.yml中添加如下配置
#默认分词器,索引
index.analysis.analyzer.default.type: index_ansj

#默认分词器,查询
index.analysis.analyzer.default_search.type: query_ansj

然后启动elasticsearch，结果报错 node setting must not contain any index level settings

**Comment by shi-yuan** [comment]
elasticsearch 6.0.0是不支持在elasticsearch.yml里配置index.analysis.analyzer.default.type，需要加在index settings里

**Comment by shi-yuan** [comment]
```json
{
  "settings": {
    "analysis": {
      "analyzer": {
        "default": {
          ...
        }
      }
    }
  }
}
```

**Comment by rtygbwwwerr** [comment]
直接在python代码里设置吗?

**Comment by shi-yuan** [comment]
建索引的时候，可以设置settings的

**Comment by shi-yuan** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-create-index.html#create-index-settings

**Comment by rtygbwwwerr** [comment]
python里边像这样写吗？
es = Elasticsearch()   
 es.indices.create(
        index=index_name,
        body={

  "settings": {
    "analysis": {
      "analyzer": {
        "default": ...
      }
    }
  }
}

    )

**Comment by shi-yuan** [comment]
接口是基于restful，dsl对的话，是可以的

**Comment by shi-yuan** [comment]
https://github.com/NLPchina/elasticsearch-analysis-ansj/issues/121
