### ISSUE TITLE
ES 6.3.0  ansj索引分词不生效

### ISSUE THREAD

**Issue by belivem** [NLPchina/elasticsearch-analysis-ansj#123]
输入:
GET /_analyze
{
  "analyzer": "index_ansj",
  "text": "我想看南京市长江大桥"
}

输出:
{
  "tokens": [
    {
      "token": "我",
      "start_offset": 0,
      "end_offset": 1,
      "type": "r",
      "position": 0
    },
    {
      "token": "想",
      "start_offset": 1,
      "end_offset": 2,
      "type": "v",
      "position": 1
    },
    {
      "token": "看",
      "start_offset": 2,
      "end_offset": 3,
      "type": "v",
      "position": 2
    },
    {
      "token": "南京市",
      "start_offset": 3,
      "end_offset": 6,
      "type": "ns",
      "position": 3
    },
    {
      "token": "长江",
      "start_offset": 6,
      "end_offset": 8,
      "type": "ns",
      "position": 4
    },
    {
      "token": "大桥",
      "start_offset": 8,
      "end_offset": 10,
      "type": "n",
      "position": 5
    }
  ]
}

这种情况使得索引分词和查询分词 一模一样啊！  可能会遗漏一些关键字！

**Comment by ansjsun** [comment]
索引分词如果想生效需要挂载自定义词典。。

如你将南京市长江大桥。加入到词典中。

结果会是 `南京市长江大桥  南京市 长江  大桥 ` 这四个结果

**Comment by belivem** [comment]
真实感谢您了！  后来我发现我的问题在于配置文件中 没有加载默认的分词词典
