### ISSUE TITLE
添加词库接口咨询

### ISSUE THREAD

**Issue by leyoliu1987** [NLPchina/elasticsearch-analysis-ansj#124]
您好，请问一下tag5.3.0有没有提供可用的接口供调用添加自己行业的词库到默认词库啊。如何操作啊。
想在项目中用这个工具，很好用。

**Comment by ansjsun** [comment]
我是这么做的再。elasticsearch.yml 增加

`ansj_config: http://192.168.10.9:9095/api/MSP/MssDictApi/config
`

相当于配置文件通过restful api获取。

http://192.168.10.9:9095/api/MSP/MssDictApi/config 的内容如下

`
isRealName=true
isNameRecognition=true
isNumRecognition=true
isQuantifierRecognition=true
custom_qdzw=http://192.168.10.9:9095/api/MSP/MssDictApi/dict?type=custom&id=1
dic_默认词表=http://192.168.10.9:9095/api/MSP/MssDictApi/dict?type=dic&id=77
stop_停用词表=http://192.168.10.9:9095/api/MSP/MssDictApi/dict?type=stop&id=78
ambiguity_歧义词表=http://192.168.10.9:9095/api/MSP/MssDictApi/dict?type=ambiguity&id=80
synonyms_default=http://192.168.10.9:9095/api/MSP/MssDictApi/dict?type=synonyms&id=126
dic_justtest=http://192.168.10.9:9095/api/MSP/MssDictApi/dict?type=dic&id=127
dic_aaaa=http://192.168.10.9:9095/api/MSP/MssDictApi/dict?type=dic&id=128
synonyms_tongyici=http://192.168.10.9:9095/api/MSP/MssDictApi/dict?type=synonyms&id=160
dic_sentiment=http://192.168.10.9:9095/api/MSP/MssDictApi/dict?type=dic&id=177
custom_suggest=http://192.168.10.9:9095/api/MSP/MssDictApi/dict?type=custom&id=178
custom_qingdao_area=http://192.168.10.9:9095/api/MSP/MssDictApi/dict?type=custom&id=190
custom_bumen=http://192.168.10.9:9095/api/MSP/MssDictApi/dict?type=custom&id=191
custom_esgcc=http://192.168.10.9:9095/api/MSP/MssDictApi/dict?type=custom&id=194
dic_qingdao=http://192.168.10.9:9095/api/MSP/MssDictApi/dict?type=dic&id=195
stop_qingdao=http://192.168.10.9:9095/api/MSP/MssDictApi/dict?type=stop&id=196
custom_qingdao_pinyin=http://192.168.10.9:9095/api/MSP/MssDictApi/dict?type=custom&id=197
dic_dizhi=http://192.168.10.9:9095/api/MSP/MssDictApi/dict?type=dic&id=198
custom_qingdao_units=http://192.168.10.9:9095/api/MSP/MssDictApi/dict?type=custom&id=200
dic_ansj=http://192.168.10.9:9095/api/MSP/MssDictApi/dict?type=dic&id=201
dic_gov_keyword=http://192.168.10.9:9095/api/MSP/MssDictApi/dict?type=dic&id=202
synonyms_CouncilDep=http://192.168.10.9:9095/api/MSP/MssDictApi/dict?type=synonyms&id=209
dic_ZWkeywords=http://192.168.10.9:9095/api/MSP/MssDictApi/dict?type=dic&id=211
dic_ucs_organization=http://192.168.10.9:9095/api/MSP/MssDictApi/dict?type=dic&id=212
dic_ucs_classification=http://192.168.10.9:9095/api/MSP/MssDictApi/dict?type=dic&id=214
dic_test=http://192.168.10.9:9095/api/MSP/MssDictApi/dict?type=dic&id=230
dic_dianshang=http://192.168.10.9:9095/api/MSP/MssDictApi/dict?type=dic&id=232
`


这样这里面的词典。都是通过api提供的。

当词典发生改变的时候。需要通知下es。es重新reload词典

`TransportAddress address = mssEsClient.getClient().admin().cluster().nodesInfo(new NodesInfoRequest()).actionGet().getNodesMap().entrySet().stream().findFirst().get()
				.getValue().getHttp().getAddress().publishAddress();
		Response response = Http.get("http://" + address + "/_ansj/flush/dic?key=" + find.getString("name"), 100000);
`
find.getString("name") 应该是词典的key 。就是 dic_ansj

**Comment by leyoliu1987** [comment]
![image](https://user-images.githubusercontent.com/32660478/42418966-19c6549e-82de-11e8-9fa5-ee62cf648342.png)
请问这些url里的词是什么格式啊？

**Comment by leyoliu1987** [comment]
还有你这个dic_ansj词典是添加的增量部分的词还是包含所有的全量词啊。感谢

**Comment by ansjsun** [comment]
1.全量词。 返回的内容和词典格式无二

![image](https://user-images.githubusercontent.com/1221947/42419083-91f7e638-82e0-11e8-8747-a881a2b5fc9b.png)
l乱码是因为浏览器编码问题。请自行忽略。返回内容文本必须是utf-8的

2.每次刷新是刷新整个词典

http://ip:9200/_ansj/flush/dic?key=dic_ansj

调用这个接口。则分词器重新加载这个词典。

**Comment by leyoliu1987** [comment]
每次是什么时机触发刷新呢？添加词直接在这个词库添加吗。那根直接在默认的那种词库添加有什么区别吗？

**Comment by yang1** [comment]
@ansjsun 想问下api接口返回格式，是如何生成的？有代码实例么？谢谢了。

我试过api接口按数组方式返回，配置dic=http://127.0.0.1:8008/api/es
启动es调用后，间索引，调用es分词链接后，分词不成功。
如下：
[
"无民事行为能力	ins	20000 ",
"你好星济大数据集团	ins	20000 ",
"大白定期寿险 ins	20000 ",
"大智慧公司	ins	20000 ",
"中国人寿资产管理公司	ins	20000"
]

**Comment by ansjsun** [comment]
@yang1 不是json格式.. 只是txt 和文本打开词典格式一致 

```
中国    ns    1000
````
