### ISSUE TITLE
index_ansj未起作用

### ISSUE THREAD

**Issue by 3031213101** [NLPchina/elasticsearch-analysis-ansj#125]
在建index_ansj索引后，发现新增进去的内容，没有按index_ansj进行分词索引，而是按query_ansj进行的分析索引，不知道是哪里有问题，请指教一下！谢谢。
mapping如下：
`"mappings": {
"maintest": {
"_all": {
"enabled": false
},
"properties": {
"post_date": {
"type": "date"
},
"name": {
"search_analyzer": "query_ansj",
"analyzer": "index_ansj",
"type": "text"
},
"message": {
"type": "text",
"fields": {
"keyword": {
"ignore_above": 256,
"type": "keyword"
}
}
}
}
}`

name字段设置了index_ansj和query_ansj

我们采用了测试词：中华人民共和国环境保护部  中华人民共和国农业部
分词出来的效果是：中华人民共和国 环境 保护 部 中华人民共和国 农业部

而在 http://demo.nlpcn.org这个在线ansj分词器里面，进行索引分词结果是：
中华人民共和国环境保护部 中华人民共和国 中华人民 中华 华人 人民共和国 人民 民共 共和国 共和 和国 环境保护部 环境保护 环境 保护部 保护 中华人民共和国农业部 中华人民共和国农业 中华人民共和国 中华人民 中华 华人 人民共和国 人民 民共 共和国 共和 和国 国农 农业部 农业 业部

差别很大？不知道哪里出问题了

**Comment by shi-yuan** [comment]
没有挂载默认词典
