### ISSUE TITLE
配置mysql加载词库问题

### ISSUE THREAD

**Issue by yang1** [NLPchina/elasticsearch-analysis-ansj#126]
ansj.cfg.yml中配置ansj_library.properties文件：
ansj_config: config/elasticsearch-analysis-ansj/ansj_library.properties

然后在ansj_library.properties文件里配置（配置文件加载没问题）
dic=jdbc://jdbc:mysql://172.16.100.49:3306/algorithm_debang?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull|algorithm|123456|select name as name,nature,freq from all_hanlp_1
加载数据库方式出错：
[2018-07-26T15:19:55,409][ERROR][o.a.l.DicLibrary         ] Init dic library error :org.ansj.exception.LibraryException: err to load by jdbc jdbc:mysql://172.16.100.49:3306/algorithm_debang?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull|algorithm|********|select name as name,nature,freq from all_hanlp_1, path: jdbc://jdbc:mysql://172.16.100.49:3306/algorithm_debang?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull|algorithm|123456|select name as name,nature,freq from all_hanlp_1
我这边配置有问题么?谢谢

**Comment by shi-yuan** [comment]
[plugin-security.policy](https://github.com/NLPchina/elasticsearch-analysis-ansj/blob/master/src/main/plugin-metadata/plugin-security.policy)文件的

permission java.net.SocketPermission "*:*", "accept,connect,resolve";

打开了吗？

**Comment by yang1** [comment]
我在plugin-security.policy文件增加了
grant {
  permission java.lang.RuntimePermission "getClassLoader";
  permission java.lang.RuntimePermission "setContextClassLoader";
  permission java.io.FilePermission "<<ALL FILES>>", "read,write";
  **permission java.net.SocketPermission "172.16.100.49:3306", "accept,connect,resolve";**
};也是报提问同样的错误。
改成：
grant {
  permission java.lang.RuntimePermission "getClassLoader";
  permission java.lang.RuntimePermission "setContextClassLoader";
  permission java.io.FilePermission "<<ALL FILES>>", "read,write";
  **permission java.net.SocketPermission "172.16.100.49:3306", "accept,connect,resolve";**
}也是提问同样的错误
还有别的需要配置？

**Comment by shi-yuan** [comment]
plugin目录下有jdbc驱动吗？

**Comment by yang1** [comment]
没有驱动，需要配什么版本的jdbc的驱动？您这边能否把配置jdbc的流程写下来么？谢谢了。

**Comment by yang1** [comment]
谢谢了，我在plugins/elasticsearch-analysis-ansj加了mysql-connector-java-5.1.46.jar这个包，可以访问mysql数据了

**Comment by jiyourui** [comment]
@yang1 你使用的是哪个版本，我按照你的方式配置了之后依然还有这种问题，我使用的是5.4.0和6.1.4这两个版本

**Comment by yang1** [comment]
es我用的是5.6.1这个版本

**Comment by qq284171290** [comment]
@yang1 你确定jdbc 安装在了 plugins/elasticsearch-analysis-ansj目录下吗，这里还是不行

**Comment by xiahe-debug** [comment]
报错Using REST wrapper from plugin org.elasticsearch.xpack.security.Security  @yang1  您确定jdbc是安装在plugins/elasticsearch-analysis-ansj下面mysql-connector-java-X.X.X.jar 吗
