### ISSUE TITLE
url测试分词器报错

### ISSUE THREAD

**Issue by hrdxwandg** [NLPchina/elasticsearch-analysis-ansj#127]
http://localhost:9200/music/music/analyze?singer=%E5%BC%A0%E5%9B%BD%E8%8D%A3%20zhang%20guo%20rong&analyzer=index_ansj

用以上url测试分词结果，报错如下：
`{
error: {
root_cause: [
{
type: "illegal_argument_exception",
reason: "request [/music/music/analyze] contains unrecognized parameters: [analyzer], [singer]"
}
],
type: "illegal_argument_exception",
reason: "request [/music/music/analyze] contains unrecognized parameters: [analyzer], [singer]"
},
status: 400
}`

问下怎么设置才能正确？
另外，想问下英文或者拼音类的是怎么切分的？是按照空格切分吗？

谢谢

**Comment by hrdxwandg** [comment]
另外，想问下英文或者拼音类的是怎么切分的？是按照空格切分吗？

**Comment by shi-yuan** [comment]
```
curl -XGET "localhost:9200/music/_analyze?pretty" -H "Content-Type: application/json" -d'
{
  "text": "张国荣 zhang guo rong",
  "analyzer": "index_ansj"
}
'
```

**Comment by shi-yuan** [comment]
英文或者拼音是按空格的

**Comment by hrdxwandg** [comment]
谢谢

**Comment by shi-yuan** [comment]
可以配置停用词的

**Comment by hrdxwandg** [comment]
好的
