### ISSUE TITLE
请问一下，用6.4版本的es，要使用自定义词典ansj.cfg.yml应该怎么写呢？

### ISSUE THREAD

**Issue by xuganggogo** [NLPchina/elasticsearch-analysis-ansj#132]
我尝试了一阵子
Caused by: org.elasticsearch.index.mapper.MapperParsingException: analyzer [first_index_dic] not found for field [eName]
一直告诉我找不到自定义的分词器

**Comment by shi-yuan** [comment]
https://github.com/NLPchina/elasticsearch-analysis-ansj#242或520以上

**Comment by xuganggogo** [comment]
感谢回复！
我的ansj.cfg.yml如下 

# 全局变量配置方式一
`ansj:
  #默认参数配置
  isNameRecognition: true #开启姓名识别
  isNumRecognition: true #开启数字识别
  isQuantifierRecognition: true #是否数字和量词合并
  isRealName: false #是否保留真实词语,建议保留false

  #用户自定词典配置
  dic: plugins/elasticsearch-analysis-ansj/default.dic #也可以写成 file://default.dic , 如果未配置dic,则此词典默认加载
  dic_1: plugins/elasticsearch-analysis-ansj/self/default.dic
  dic_2: plugins/elasticsearch-analysis-ansj/self/name.dic
  # http方式加载
  #dic_d1: http://xxx/xx.dic
  # jar中文件加载
  #dic_d2: jar://org.ansj.dic.DicReader|/dic2.dic
  # 从数据库中加载
  #dic_d3: jdbc://jdbc:mysql://xxxx:3306/ttt?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull|username|password|select name as name,nature,freq from dic where type=1
  # 从自定义类中加载,YourClas  extends PathToStream
  #dic_d3: class://xxx.xxx.YourClas|ohterparam

  #过滤词典配置
  #stop: http,file,jar,class,jdbc 都支持
  #stop_key1: ...

  #歧义词典配置
  #ambiguity: http,file,jar,class,jdbc 都支持
  #ambiguity_key1: ...

  #同义词词典配置
  #synonyms: http,file,jar,class,jdbc 都支持
  #synonyms_key1: ...
  synonyms_1: plugins/elasticsearch-analysis-ansj/self/synonyms.dic


# 全局变量配置方式二 通过配置文件的方式配置,优先级高于es本身的配置
# ansj_config: ansj_library.properties
#http,file,jar,class,jdbc 都支持,格式参见ansj_library.properties

# 配置自定义分词器
index:
  analysis:
    tokenizer :
      first_index_tokenizer :
        type : index_ansj
        dic: dic
        stop: stop
        synonyms: synonyms_1
        isNameRecognition: true
        isNumRecognition: true
        isQuantifierRecognition: true
        isRealName: false
        
      first_query_tokenizer :
        type : query_ansj
        dic: dic
        stop: stop
        synonyms: synonyms_1
        isNameRecognition: true
        isNumRecognition: true
        isQuantifierRecognition: true
        isRealName: false

    analyzer:
      first_index_dic:
        type: custom
        tokenizer: first_index_tokenizer
        
      first_query_dic:
        type: custom
        tokenizer: first_query_tokenizer`


mapping中指定分词器
`"eName": {
				"analyzer": "first_index_dic",
				"type": "text"
			},`

能帮忙指出错误吗？

**Comment by xuganggogo** [comment]
感谢回复！
我的ansj.cfg.yml如下

`# 全局变量配置方式一
ansj:
  #默认参数配置
  isNameRecognition: true #开启姓名识别
  isNumRecognition: true #开启数字识别
  isQuantifierRecognition: true #是否数字和量词合并
  isRealName: false #是否保留真实词语,建议保留false

  #用户自定词典配置
  dic: plugins/elasticsearch-analysis-ansj/default.dic #也可以写成 file://default.dic , 如果未配置dic,则此词典默认加载
  dic_1: plugins/elasticsearch-analysis-ansj/self/default.dic
  dic_2: plugins/elasticsearch-analysis-ansj/self/name.dic
 
  #stop: http,file,jar,class,jdbc 都支持
  #stop_key1: ...

  #歧义词典配置
  #ambiguity: http,file,jar,class,jdbc 都支持
  #ambiguity_key1: ...

  #同义词词典配置
  #synonyms: http,file,jar,class,jdbc 都支持
  #synonyms_key1: ...
  synonyms_1: plugins/elasticsearch-analysis-ansj/self/synonyms.dic


# 全局变量配置方式二 通过配置文件的方式配置,优先级高于es本身的配置
# ansj_config: ansj_library.properties
#http,file,jar,class,jdbc 都支持,格式参见ansj_library.properties

# 配置自定义分词器
index:
  analysis:
    tokenizer :
      first_index_tokenizer :
        type : index_ansj
        dic: dic
        stop: stop
        synonyms: synonyms_1
        isNameRecognition: true
        isNumRecognition: true
        isQuantifierRecognition: true
        isRealName: false
        
      first_query_tokenizer :
        type : query_ansj
        dic: dic
        stop: stop
        synonyms: synonyms_1
        isNameRecognition: true
        isNumRecognition: true
        isQuantifierRecognition: true
        isRealName: false

    analyzer:
      first_index_dic:
        type: custom
        tokenizer: first_index_tokenizer
        
      first_query_dic:
        type: custom
        tokenizer: first_query_tokenizer
        `
	
	
mapping中指定分词器
"eName": { "analyzer": "first_index_dic", "type": "text" },

能帮忙指出错误吗？

**Comment by xuganggogo** [comment]
感谢回复！
我的ansj.cfg.yml如下

`
ansj:
  #默认参数配置
  isNameRecognition: true #开启姓名识别
  isNumRecognition: true #开启数字识别
  isQuantifierRecognition: true #是否数字和量词合并
  isRealName: false #是否保留真实词语,建议保留false

  dic: plugins/elasticsearch-analysis-ansj/default.dic #也可以写成 file://default.dic , 如果未配置dic,则此词典默认加载
  dic_1: plugins/elasticsearch-analysis-ansj/self/default.dic
  dic_2: plugins/elasticsearch-analysis-ansj/self/name.dic
 
  synonyms_1: plugins/elasticsearch-analysis-ansj/self/synonyms.dic

index:
  analysis:
    tokenizer :
      first_index_tokenizer :
        type : index_ansj
        dic: dic
        stop: stop
        synonyms: synonyms_1
        isNameRecognition: true
        isNumRecognition: true
        isQuantifierRecognition: true
        isRealName: false
        
      first_query_tokenizer :
        type : query_ansj
        dic: dic
        stop: stop
        synonyms: synonyms_1
        isNameRecognition: true
        isNumRecognition: true
        isQuantifierRecognition: true
        isRealName: false

    analyzer:
      first_index_dic:
        type: custom
        tokenizer: first_index_tokenizer
        
      first_query_dic:
        type: custom
        tokenizer: first_query_tokenizer
`

mapping中指定分词器
"eName": { "analyzer": "first_index_dic", "type": "text" },

能帮忙指出错误吗？（格式不太会调整，有点乱）

**Comment by shi-yuan** [comment]
哈哈哈，自定义分词器不是在ansj.cfg.yml配置的噢

**Comment by shi-yuan** [comment]
````
curl -X PUT "localhost:9200/my_index" -H 'Content-Type: application/json' -d'
{
  "settings": {
    "analysis": {
      "tokenizer": {
        "first_index_tokenizer": {
          "type": "index_ansj",
          "dic": ["dic"],
          "stop": ["stop"],
          "synonyms": ["synonyms_1"],
          "isNameRecognition": true
          "isNumRecognition": true
          "isQuantifierRecognition": true
          "isRealName": false
        },
        "first_query_tokenizer": {
          "type": "query_ansj",
          "dic": ["dic"],
          "stop": ["stop"],
          "synonyms": ["synonyms_1"],
          "isNameRecognition": true
          "isNumRecognition": true
          "isQuantifierRecognition": true
          "isRealName": false
        },
      },
      "analyzer": {
        "first_index_dic": {
          "type": "custom",
          "tokenizer": "first_index_tokenizer"
        },
        "first_index_dic": {
          "type": "custom",
          "tokenizer": "first_query_tokenizer"
        }
      }
    }
  }
}
'
````

**Comment by xuganggogo** [comment]
感谢大大！！
加载多个词库我是这样写的好像也支持，用逗号分隔，如下
`"dic": "dic,dic_1,dic_2",`
