### ISSUE TITLE
dic_d1词典不生效

### ISSUE THREAD

**Issue by PKFresher** [NLPchina/elasticsearch-analysis-ansj#138]
dic_d1 设置了分词  足力健,但是使用 query_ansj 没有生效
http://127.0.0.1:9200/item/_analyze?analyzer=query_ansj&text=%E8%B6%B3%E5%8A%9B%E5%81%A5
`
{
tokens: [
{
token: "足",
start_offset: 0,
end_offset: 1,
type: "a",
position: 0
},
{
token: "力",
start_offset: 1,
end_offset: 2,
type: "n",
position: 1
},
{
token: "健",
start_offset: 2,
end_offset: 3,
type: "nr",
position: 2
}
]
}
`设置 了dic_d1 未生效
http://127.0.0.1:9200/_cat/ansj/config
`{
ambiguity: [ ],
dic_d1: "D:\tools\tems\brand_dict",
stop: [ ],
synonyms: [ ],
crf: [
"crf"
],
isQuantifierRecognition: "true",
isRealName: "false",
isNameRecognition: "true",
isNumRecognition: "true",
dic: [
"dic_d1",
"dic"
]
}`

但在下面的查询中生效了
http://127.0.0.1:9200/_cat/ansj?text=%E8%B6%B3%E5%8A%9B%E5%81%A5%E8%80%81%E4%BA%BA%E9%9E%8B&type=query_ansj&dic=dic_d1,dic
`{
result: [
{
name: "足力健",
nature: "userDefine",
offe: 0,
realName: "足力健",
synonyms: null
},
{
name: "老人",
nature: "n",
offe: 3,
realName: "老人",
synonyms: null
},
{
name: "鞋",
nature: "n",
offe: 5,
realName: "鞋",
synonyms: null
}
]
}`

**Comment by shi-yuan** [comment]
需要影响全局分词器的话，需要是默认的词典key：dic。
如果是dic_d1，使用的话，需要自定义分词器

**Comment by runningship** [comment]
听不懂，到底什么意思
dic: plugins\elasticsearch-analysis-ansj\default.dic
dic_d1: plugins\elasticsearch-analysis-ansj\user\mpm.dic
这样配置没效果

**Comment by PKFresher** [comment]
1.确认下配置读取到词典文件.
2.如果想让dic_d1生效,需要配置自定义分词器.  如果觉得麻烦可以将mpm.dic词典 全部写入 default.dic.
