### ISSUE TITLE
有点复杂的分词需求，求大神看看

### ISSUE THREAD

**Issue by xuganggogo** [NLPchina/elasticsearch-analysis-ansj#139]
举个例子，搜索“我今天想看恐怖电影“。
我定一个词典只有“恐怖”、“电影”这两个词。
我希望查询的时候，分词器会把这句话只分词为“恐怖”“电影”，而不要把“我”“今天”拿去搜索。
请大神指导一下，我需要怎么弄呢？

**Comment by shi-yuan** [comment]
使用[Keep Words Token Filter](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-keep-words-tokenfilter.html)或者[Keep Types Token Filter](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-keep-types-tokenfilter.html)

**Comment by xuganggogo** [comment]
感谢~结贴~
