### ISSUE TITLE
索引名称应该如何去改。当前是index_ansj。 需要改成ansj_index

### ISSUE THREAD

**Issue by Reyoo** [NLPchina/elasticsearch-analysis-ansj#141]

**Comment by shi-yuan** [comment]
索引名称不能改吧，可以重建索引，或者弄个别名吧

**Comment by Reyoo** [comment]
> 
> 
> 索引名称不能改吧，可以重建索引，或者弄个别名吧

目前是这样。我们得es2.0版本用得分词器 是"analyzer": "ansj_index",   但是这个的5.4.3版本按照完后。是"analyzer": "index_ansj",   我希望通过修改源码的方式 修改成和我们2版本一致的方式，以便于迁移。
所以现在希望能得到解决的思路

**Comment by shi-yuan** [comment]
改源码也可以，不改源码的话，加自定义分词器就行

**Comment by Reyoo** [comment]
> 
> 
> 改源码也可以，不改源码的话，加自定义分词器就行

我尝试下自定义。多谢

**Comment by shi-yuan** [comment]
如果改源码，可以看看这里，这里是注册的：https://github.com/NLPchina/elasticsearch-analysis-ansj/blob/master/src/main/java/org/ansj/elasticsearch/plugin/AnalysisAnsjPlugin.java

如果自定义分词器，可以参考配置文件说明：https://github.com/NLPchina/elasticsearch-analysis-ansj#%E5%88%86%E8%AF%8D%E6%96%87%E4%BB%B6%E9%85%8D%E7%BD%AE

**Comment by Reyoo** [comment]
> 
> 
> 如果改源码，可以看看这里，这里是注册的：https://github.com/NLPchina/elasticsearch-analysis-ansj/blob/master/src/main/java/org/ansj/elasticsearch/plugin/AnalysisAnsjPlugin.java
> 
> 如果自定义分词器，可以参考配置文件说明：https://github.com/NLPchina/elasticsearch-analysis-ansj#%E5%88%86%E8%AF%8D%E6%96%87%E4%BB%B6%E9%85%8D%E7%BD%AE

自定义分词器，不限于”# 类型支持base_ansj, index_ansj, query_ansj, dic_ansj, nlp_ansj“ 这些吗

**Comment by shi-yuan** [comment]
自定义分词器的名字，只要符合规范，可以任意写的

**Comment by Reyoo** [comment]
> 
> 
> 自定义分词器的名字，只要符合规范，可以任意写的
安装后，启动es 日志中出现这样一个问题。

load ansj config: /home/es5/elasticsearch-5.4.3/plugins/elasticsearch-analysis-ansj/config/ansj.cfg.yml
[2018-11-21T15:38:51,967][WARN ][o.a.u.MyStaticValue      ] not find ansj_library.properties. and err {} i think it is a bug!
[2018-11-21T15:38:51,968][WARN ][o.a.u.MyStaticValue      ] not find library.properties. and err {} i think it is a bug!

我想问一下，是因为我少部署了什么东西吗

**Comment by shi-yuan** [comment]
这些警告，可以不用理会

**Comment by Reyoo** [comment]
#########

index:
  analysis:
    tokenizer :
      my_dic :
        type : ansj_index
        dic: dic
        stop: stop
        ambiguity: ambiguity
        synonyms: synonyms
        isNameRecognition: true
        isNumRecognition: true
        isQuantifierRecognition: true
        isRealName: false

    analyzer:
      my_dic:
        type: custom
        tokenizer: default.dic

这个是我的自定义注解部分。。 但是没有起作用 。别名还是index_ansj

**Comment by shi-yuan** [comment]
curl -X PUT "localhost:9200/my_index" -H 'Content-Type: application/json' -d'
{
  "settings": {
    "analysis": {
      "analyzer": {
        "ansj_index": {
          "type": "custom",
          "tokenizer": "index_ansj"
        }
      }
    }
  }
}
'

**Comment by Reyoo** [comment]
感谢。 通过修改源码AnalysisAnsjPlugin.java  重新打包部署到${ES.HOME}/plugins  下，然后修改plugins/config 下 自定义注解。完成。十分感谢

**Comment by Reyoo** [comment]
extra.put("自定义注解名称", (indexSettings, env, name, settings) -> new AnsjAnalyzerProvider(indexSettings, name, settings));
