### ISSUE TITLE
请教数字字母汉字的分词问题

### ISSUE THREAD

**Issue by ycl1680** [NLPchina/elasticsearch-analysis-ansj#147]
词：7A部门（不希望被分开）
加入自定义歧义词词典中，刷新生效
分词结果是["7","A","部门"]
有什么解决办法吗

**Comment by ansjsun** [comment]
词典加入 7a部门 记得小写

**Comment by ycl1680** [comment]
> 词典加入 7a部门 记得小写

是大小写影响的
