### ISSUE TITLE
如何自定义分词

### ISSUE THREAD

**Issue by programerzhang** [NLPchina/elasticsearch-analysis-ansj#154]
大大你好，
   自定义分词的意义是指自己可以实现自己的分词么？
   有这样一个需求，遇到英文时，比如  ABCDEFG,需要拆分为 ABCD  EFG每四个字母拆分，这种需求是否在自定义分词中实现，是否需要在源码中更改呢

**Comment by ansjsun** [comment]
在业务之外修改比较合适
判断词性 和长度。写自己的业务

**Comment by programerzhang** [comment]
> 在业务之外修改比较合适
> 判断词性 和长度。写自己的业务

感谢回复，意思是在搜索词进入搜索之前对词进行处理么？
