### ISSUE TITLE
es版本6.4.3，停止词空格没起作用

### ISSUE THREAD

**Issue by hanxiaolin** [NLPchina/elasticsearch-analysis-ansj#155]
分词始终会把空格分出来，参考https://github.com/NLPchina/elasticsearch-analysis-ansj/issues/27
使用了正则模式也还是不行，我这边确定我引用同义词文件是确定生效了，不知道为啥过滤空格怎么就是行不通。。。
![image](https://user-images.githubusercontent.com/10021991/54326610-e462a780-4641-11e9-8305-f51be879c5b0.png)

**Comment by shi-yuan** [comment]
词典生效了么？词典内容呢？

**Comment by hanxiaolin** [comment]
> 词典生效了么？词典内容呢？

确定生效了，我测试加了个停止词”国“没问题，词典内容也没问题，我这边是建立index分析器时候使用的es自带的stopwords_path地址。
我换了个方式使用ansj自带的配置文件设置停止词就生效了, 目前已经解决。

**Comment by ansjsun** [comment]
停用词 用/s+试试 正则




在2019年03月14日 18:38，hanxiaolin 写道：

Closed #155.
