### ISSUE TITLE
分词问题

### ISSUE THREAD

**Issue by jlren** [NLPchina/elasticsearch-analysis-ansj#157]
es版本5.5.2
问题1：通过_ansj/flush/dic 刷新，后台总是报异常：
java.lang.NullPointerException
	at org.ansj.elasticsearch.action.TransportAnsjAction.flushDic(TransportAnsjAction.java:357)
这是因为ansj.cfg.yml配置异常吗（没配歧义、同义词典），现在都是修改词典后要集群重启后才生效；
问题2：通过http方式加载dic没生效，ansj.cfg.yml也配置了自定义分词；
问题3：求大佬微信或qq

**Comment by shi-yuan** [comment]
没生效？用5.x分支，重新打个包吧，之前的有个问题

**Comment by jlren** [comment]
您好，非常高兴您能回复，
   对的，没有生效，下面是我的配置：


# 全局变量配置方式一
ansj:
  #默认参数配置
  isNameRecognition: true #开启姓名识别
  isNumRecognition: true #开启数字识别
  isQuantifierRecognition: true #是否数字和量词合并
  isRealName: false; #是否保留真实词语,建议保留false


  #用户自定词典配置
  dic: file:///opt/elasticsearch/elasticsearch-5.5.2/plugins/elasticsearch-analysis-ansj/default.dic #也可以写成 file://default.dic , 如果未配>置dic,则此词典默认加载
  # http方式加载
  dic_d1: http://xxxx:14567/es-dic/custom.dic
  stop: http://xxxx:14567/es-dic/stop.dic
  
# 配置自定义分词器
index:
  analysis:
    tokenizer :
      my_dic :
        # 类型支持base_ansj, index_ansj, query_ansj, dic_ansj, nlp_ansj
        type : dic_ansj
        dic: "dic,dic_d1"
        stop: stop
        ambiguity: ambiguity
        synonyms: synonyms
        isNameRecognition: true
        isNumRecognition: true
        isQuantifierRecognition: true
        isRealName: false


  analyzer:
    my_dic:
      type: custom
      tokenizer: my_dic



集群动的情况下，执行/_ansj/flush/dic，报异常：



这是我现在plugin包的情况，重新打包是只要打elasticsearch-analysis-ansj-5.5.2.0.jar 还是也要打ansj_seg-5.1.3.jar这个包？

方便留个微信吗？方便交流


------------------ 原始邮件 ------------------
发件人: "shiyuan"<notifications@github.com>;
发送时间: 2019年3月29日(星期五) 晚上9:19
收件人: "NLPchina/elasticsearch-analysis-ansj"<elasticsearch-analysis-ansj@noreply.github.com>;
抄送: "逆转"<704897596@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [NLPchina/elasticsearch-analysis-ansj] 分词问题 (#157)




没生效？用5.x分支，重新打个包吧，之前的有个问题

**Comment by jlren** [comment]
用5.x分支，重新打个包，放入plugins目录下，发现对之前的索引会有影响，打不开，创建索引也会报异常

**Comment by shi-yuan** [comment]
不能直接，打包，需要改pom的es版本为5.5.2，然后重新打包

**Comment by shi-yuan** [comment]
不用打包ansj_seg，重新打包插件就行

**Comment by shi-yuan** [comment]
QQ：1006482147
