### ISSUE TITLE
5.6.16建索引的时候报java.lang.UnsupportedOperationException: null的错

### ISSUE THREAD

**Issue by boxlau** [NLPchina/elasticsearch-analysis-ansj#160]
按照命令
> ./bin/elasticsearch-plugin install https://github.com/NLPchina/elasticsearch-analysis-ansj/releases/download/v5.6.16/elasticsearch-analysis-ansj-5.6.16.0-release.zip

安装插件，安装过程正常，没有报错。然后执行参考实例

```
curl -XPUT 127.0.0.1:9200/test -d '{
    "settings" : {
        "number_of_shards" : 1,
        "number_of_replicas" : 0

    },
    "mappings" : {
        "test" : {
            "_all" : { "enabled" : false },
            "properties" : {
                "name" : { "type" : "string", "analyzer" : "index_ansj", "search_analyzer" : "query_ansj" }
            }
        }
    }
}'
```

的时候，会报错，错误信息是
![909156582](https://user-images.githubusercontent.com/17563070/55778187-cc613500-5ad4-11e9-8a15-7c51517dc702.jpg)

请问是我哪里没有配置正确吗？这个报错似乎是没有读到配置信息？

**Comment by shi-yuan** [comment]
有bug，在5.x分支，重新打包吧

**Comment by boxlau** [comment]
重新获取源码打包了，可以正常创建索引，没有报这个错了。
但是在插入数据的时候，会报NoSuchMethodError
![1518905161](https://user-images.githubusercontent.com/17563070/55863563-5a105380-5bad-11e9-9a52-916fe9841af0.jpg)
这个是为什么呢？

**Comment by shi-yuan** [comment]
不应该的啊，这个bug已经修了啊

https://github.com/NLPchina/elasticsearch-analysis-ansj/blob/5.x/src/main/java/org/ansj/elasticsearch/action/TransportAnsjAction.java

**Comment by boxlau** [comment]
然而打包的代码的版本就是改过这个java文件之后的。。

**Comment by shi-yuan** [comment]
好吧，需要改ansj_seg的源码了

**Comment by xljhtq** [comment]
@boxlau 我也是用的5.6.16的版本，而且直接用plugin install安装的话，会报错。后来，你问题解决了吗？包括插入数据，你可以运行了吗？

**Comment by shi-yuan** [comment]
升级ansj_lucene6_plug或者ansj_lucene7_plug到最新版本，然后本地重新打包
