### ISSUE TITLE
7.X的版本啥时候出来呢？？

### ISSUE THREAD

**Issue by jiyourui** [NLPchina/elasticsearch-analysis-ansj#161]

**Comment by shi-yuan** [comment]
已经出了哈，![image](https://user-images.githubusercontent.com/8057153/64486861-4acd2900-d265-11e9-9d45-7406874c73c5.png)

**Comment by shi-yuan** [comment]
https://github.com/NLPchina/elasticsearch-analysis-ansj/releases

**Comment by jiyourui** [comment]
感谢了
