### ISSUE TITLE
es集群 调用了/_ansj/flush/config导致刷新接口/_ansj/flush/dic失效

### ISSUE THREAD

**Issue by YeLuoXu** [NLPchina/elasticsearch-analysis-ansj#164]
通过插件的master版本编译了es的版本为6.7.1
正常情况：调用词典刷新接口/_ansj/flush/dic能正常刷新词典。
异常情况：调用了/_ansj/flush/config刷新配置文件后，日志显示词典正常刷新，但是通过分词接口发现词典未生效
通过/_ansj/flush/dic正常刷新词典分词结果
![image](https://user-images.githubusercontent.com/38717689/60695282-bf37c480-9ed0-11e9-85bc-9b0130e8e234.png)
通过/_ansj/flush/config刷新词典异常结果
![image](https://user-images.githubusercontent.com/38717689/60695356-f3ab8080-9ed0-11e9-8e1e-0cbae381faa0.png)

上图停用词加上了 \s+ regex、测。
作者还在不在维护啊，这个问题目前没找到原因，求助。

**Comment by shi-yuan** [comment]
刷新没问题的

**Comment by shi-yuan** [comment]
可以试试tokenizer，tokenizer每次使用都会重新创建一个

**Comment by shi-yuan** [comment]
analyzer，没变化，是因为有缓存，构造analyzer的时候，用的GLOBAL_REUSE_STRATEGY：
```java
    CloseableThreadLocal<Object> storedValue;
    public static final Analyzer.ReuseStrategy GLOBAL_REUSE_STRATEGY = new Analyzer.ReuseStrategy() {
        public Analyzer.TokenStreamComponents getReusableComponents(Analyzer analyzer, String fieldName) {
            return (Analyzer.TokenStreamComponents)this.getStoredValue(analyzer);
        }

        public void setReusableComponents(Analyzer analyzer, String fieldName, Analyzer.TokenStreamComponents components) {
            this.setStoredValue(analyzer, components);
        }
    };
```

**Comment by YeLuoXu** [comment]
好的，知道了，感谢！

**Comment by shi-yuan** [comment]
[热更新问题已修复](https://github.com/NLPchina/elasticsearch-analysis-ansj/commit/0afbd8e4aa147841ff78e296812f867e5511799f)
