### ISSUE TITLE
项目clone下来后不能执行mvn clean install

### ISSUE THREAD

**Issue by oczjack** [NLPchina/elasticsearch-analysis-ansj#17]
如题，项目clone下来后，执行mvn clean install 报错
[ERROR] Failed to execute goal on project elasticsearch-analysis-ansj: Could not
resolve dependencies for project org.ansj:elasticsearch-analysis-ansj:jar:2.1.1
: The following artifacts could not be resolved: org.ansj:ansj_seg:jar:3.6, org.
ansj:ansj_lucene5_plug:jar:3.0: Failure to find org.ansj:ansj_seg:jar:3.6 in htt
p://repo1.maven.org/maven2/ was cached in the local repository, resolution will
not be reattempted until the update interval of repo1 has elapsed or updates are
 forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyReso
lutionException

**Comment by ansjsun** [comment]
直接下载成功的jar包吧不要自己编译了个人觉得

**Comment by ansjsun** [comment]
我的脚本是

mvn clean  compile package  然后得到zip包..解压到  ${elasticsearhc}/plugins/elasticsearch-analysis-ansj 目录下.

**Comment by ansjsun** [comment]
太久没有互动关闭了吧
