### ISSUE TITLE
关于ansj_library.properties文件配置问题

### ISSUE THREAD

**Issue by AlexYoung757** [NLPchina/elasticsearch-analysis-ansj#172]
大佬好，有一些疑问请教。如下
（1）ansj插件相关词典配置是否全部在当前文件下设置；
（2）对于同义词、停用词配置问题，已配置相关路径，但若自定义文件名字不改为stop.dic、synonyms.dic，检索时仍然报错。请问是不是一定要求文件名字一致

**Comment by shi-yuan** [comment]
建议使用绝对路径来配置，只要是文本文件，词典里内容格式是对的，文件名字应该不影响使用

**Comment by AlexYoung757** [comment]
> 建议使用绝对路径来配置，只要是文本文件，词典里内容格式是对的，文件名字应该不影响使用

感谢，已解决。
