### ISSUE TITLE
7.4版本自定义分词器找不到词典。

### ISSUE THREAD

**Issue by fuhongyuan** [NLPchina/elasticsearch-analysis-ansj#182]
请问下面的情况应该如何解决呢？
未配置全局的yml,settings配置如下:
```
{
        "index": {
            "analysis": {
                "analyzer": {
                    "index_analyzer": {
                        "type": "custom",
                        "tokenizer": "index_token"
                    }
                },
                "tokenizer": {
                    "index_token": {
                        "isQuantifierRecognition": "true",
                        "type": "index_ansj",
                        "isNameRecognition": "true",
                        "isNumRecognition": "true",
                        "dic": "test002.dic"
                    }
                }
            }
        }
    }
```
将test002.dic词典放到/elasticsearch-7.4.2/dic/test002.dic 目前下，
GET 
```
http://127.0.0.1:9200/_ansj/flush/dic/single?key=dic
```
后，使用自带的index_ansj时可以使用test002.dic中的词，但是使用自定义的index_analyzer时，提示：
```
[WARN ][o.a.l.DicLibrary         ] [MacBook] dic test002.dic not found in config 
```

**Comment by ansjsun** [comment]
是不是得刷新下





在2020年04月13日 17:06，fuhongyuan 写道：

请问下面的情况应该如何解决呢？
未配置全局的yml,settings配置如下:

{

        "index": {

            "analysis": {

                "analyzer": {

                    "index_analyzer": {

                        "type": "custom",

                        "tokenizer": "index_token"

                    }

                },

                "tokenizer": {

                    "index_token": {

                        "isQuantifierRecognition": "true",

                        "type": "index_ansj",

                        "isNameRecognition": "true",

                        "isNumRecognition": "true",

                        "dic": "test002.dic"

                    }

                }

            }

        }

    }



将test002.dicx词典放到/elasticsearch-7.4.2/dic/test002.dic 目前下，
GET

http://127.0.0.1:9200/_ansj/flush/dic/single?key=dic



后，使用自带的index_ansj时可以使用test002.dic中的词，但是使用自定义的index_analyzer时，提示：

[WARN ][o.a.l.DicLibrary         ] [MacBook] dic test002.dic not found in config

**Comment by fuhongyuan** [comment]
解决了。原因是，我以为tokenizer配置中的dic可以配置词典路径，其实配置的是在ansj.cfg.yml中配置的词典名称，词典路径只能在ansj.cfg.yml中配置。
