### ISSUE TITLE
请问下如何给分词器换别名？

### ISSUE THREAD

**Issue by Reyoo** [NLPchina/elasticsearch-analysis-ansj#184]
我们项目用的分词器比较诡异。是ansj_index。但是 启动es5.4.3 
regedit analyzer tokenizer named: base_ansj
regedit analyzer tokenizer named: index_ansj
regedit analyzer tokenizer named: query_ansj
regedit analyzer tokenizer named: nlp_ansj

想自定义分词器别名变成 ansj_index 。 请问下 怎么操作。 编译源码 AnalysisAnsjPlugin 中  extra.put("ansj_index", (indexSettings, env, name, settings) -> new AnsjAnalyzerProvider(indexSettings, name, settings)); 加入行 可以解决快照问题，但是 历史索引用的ansj_index 上传文本文件就会报错。请问下 如果修改别名

**Comment by shi-yuan** [comment]
自定义分词器，就行

**Comment by Reyoo** [comment]
重建索引啦 谢谢
