### ISSUE TITLE
7.6.2.0版本

### ISSUE THREAD

**Issue by yushanhang** [NLPchina/elasticsearch-analysis-ansj#193]
mysql  加载动态扩展词， 
启动es没有错误 。
刷新词典不报错 。
但是没有生效   

[
<img width="1440" alt="截屏2021-04-12 下午10 40 16" src="https://user-images.githubusercontent.com/45548021/114412900-1d362780-9be0-11eb-8df5-02eeb239fedc.png">
<img width="1440" alt="截屏2021-04-12 下午10 40 23" src="https://user-images.githubusercontent.com/45548021/114412912-1f988180-9be0-11eb-82f1-31d3f3a405c8.png">

](url)

**Comment by shi-yuan** [comment]
如果是通过analyzer自定义的分词器，确实是存在问题的，如果用tokenizer是ok的

#164

**Comment by shi-yuan** [comment]
通过analyzer自定义的分词器的问题，近期会考虑修复

**Comment by shi-yuan** [comment]
配置没毛病，未生效，是根本就没加载，还是刷新不起作用？

**Comment by shi-yuan** [comment]
可以的，自定义分词器，使用多个词典
````
{
...
"dic": "dic,dic_0",
"stop": "stop,stop_0",
"ambiguity": "ambiguity,ambiguity_0",
"synonyms": "synonyms,synonyms_0",
...
}
````
