### ISSUE TITLE
除修改config/ansj.cfg.yml添加自定义词典,还有其他方式添加自定义词典吗?

### ISSUE THREAD

**Issue by pinkfloyds** [NLPchina/elasticsearch-analysis-ansj#200]
准备在云es上使用ansj,需要添加自定义词典,但咨询过云厂商客服,云es不支持直接修改yml

**Comment by shi-yuan** [comment]
可以的，可以只配置一个ansj_config，这个配置的路径可以写成访问数据库的path

**Comment by pinkfloyds** [comment]
配置ansj_config也需要修改ansj.cfg.yml吧?可以通过http或其他方式修改吗?

**Comment by shi-yuan** [comment]
properties文件让改么？安装的时候，改好了上传也不行是么

**Comment by pinkfloyds** [comment]
也不支持

**Comment by shi-yuan** [comment]
安装的时候，有ansj.cfg.yml这个文件么，还是文件里没有任何内容？

**Comment by pinkfloyds** [comment]
用 GET _cat/ansj/config 可以看到有内容,但无法修改,无法上传词典文件

**Comment by shi-yuan** [comment]
目前是需要有ansj.cfg.yml这个文件的，有刷新接口不过刷新接口做的也是重新加载配置或词典

**Comment by pinkfloyds** [comment]
好的谢谢解答
