### ISSUE TITLE
能index_ansj能正常分词，但是单独使用tokenizer会提示tokenizer不存在。

### ISSUE THREAD

**Issue by cookeem** [NLPchina/elasticsearch-analysis-ansj#22]
curl -XGET 'localhost:9200/_analyze?tokenizer=index_ansj&filter=pinyin&pretty' -d '你好，我是小明的同学小强'
{
  "error" : {
    "root_cause" : [ {
      "type" : "remote_transport_exception",
      "reason" : "[node1][127.0.0.1:9300][indices:admin/analyze[s]]"
    } ],
    "type" : "null_pointer_exception",
    "reason" : null
  },
  "status" : 500
}

analyzer分词正常
curl -XGET 'localhost:9200/_analyze?analyzer=index_ansj&pretty' -d '你好，我是小明的同学小强'
{
  "tokens" : [ {
    "token" : "你好",
    "start_offset" : 0,
    "end_offset" : 2,
    "type" : "word",
    "position" : 0
  }, {
    "token" : "，",
    "start_offset" : 2,
    "end_offset" : 3,
    "type" : "word",
    "position" : 1
  }, {
    "token" : "我",
    "start_offset" : 3,
    "end_offset" : 4,
    "type" : "word",
    "position" : 2
  }, {
    "token" : "是",
    "start_offset" : 4,
    "end_offset" : 5,
    "type" : "word",
    "position" : 3
  }, {
    "token" : "小明",
    "start_offset" : 5,
    "end_offset" : 7,
    "type" : "word",
    "position" : 4
  }, {
    "token" : "的",
    "start_offset" : 7,
    "end_offset" : 8,
    "type" : "word",
    "position" : 5
  }, {
    "token" : "同学",
    "start_offset" : 8,
    "end_offset" : 10,
    "type" : "word",
    "position" : 6
  }, {
    "token" : "小强",
    "start_offset" : 10,
    "end_offset" : 12,
    "type" : "word",
    "position" : 7
  } ]
}

**Comment by cookeem** [comment]
而且很奇怪elasticsearch.log日志中有很多

**Comment by shi-yuan** [comment]
@cookeem 请问使用的是哪个版本？

**Comment by cookeem** [comment]
elasticsearch2.3.1

**Comment by shi-yuan** [comment]
这个版本依赖的ansj_lucene5_plug，版本是3.7.3，存在一个bug，不过已经被解决了，>3.7.3的ansj_lucene5_plug应该是没问题的，你可以试试

**Comment by cookeem** [comment]
升级后解决了，多谢:)

**Comment by cookeem** [comment]
我想先使用elasticsearch-analysis-ansj进行分词，然后使用elasticsearch-analysis-pinyin进行拼音处理，处理命令如下：
curl -XGET 'localhost:9200/_analyze?tokenizer=index_ansj&filter=pinyin&pretty' -d '你好，我是小明的同学小强'
但是无法输出分词后的拼音结果：
{
  "tokens" : [ {
    "token" : "你好",
    "start_offset" : 0,
    "end_offset" : 2,
    "type" : "l",
    "position" : 0
  }, {
    "token" : "，",
    "start_offset" : 2,
    "end_offset" : 3,
    "type" : "w",
    "position" : 1
  }, {
    "token" : "我",
    "start_offset" : 3,
    "end_offset" : 4,
    "type" : "r",
    "position" : 2
  }, {
    "token" : "是",
    "start_offset" : 4,
    "end_offset" : 5,
    "type" : "v",
    "position" : 3
  }, {
    "token" : "小明",
    "start_offset" : 5,
    "end_offset" : 7,
    "type" : "nr",
    "position" : 4
  }, {
    "token" : "的",
    "start_offset" : 7,
    "end_offset" : 8,
    "type" : "uj",
    "position" : 5
  }, {
    "token" : "同学",
    "start_offset" : 8,
    "end_offset" : 10,
    "type" : "n",
    "position" : 6
  }, {
    "token" : "小强",
    "start_offset" : 10,
    "end_offset" : 12,
    "type" : "nr",
    "position" : 7
  } ]
}

**Comment by cookeem** [comment]
晕死参数应该是filters不是filter

**Comment by shi-yuan** [comment]
2.3.1版本已更新，重新install，就OK了

**Comment by cookeem** [comment]
已更新，正常了，非常感谢:)
