### ISSUE TITLE
希望提供8.13.2版本

### ISSUE THREAD

**Issue by abbydev** [NLPchina/elasticsearch-analysis-ansj#236]
希望提供8.13.2版本，谢谢

**Comment by abbydev** [comment]
@shi-yuan 大佬，能不能帮忙提供一下，谢谢~

**Comment by shi-yuan** [comment]
抱歉哈，近期会发布的

**Comment by shi-yuan** [comment]
https://github.com/NLPchina/elasticsearch-analysis-ansj/releases/tag/v8.13.2
