### ISSUE TITLE
elasticsearch-analysis-ansj分词把空格也算进去了

### ISSUE THREAD

**Issue by jack-nie** [NLPchina/elasticsearch-analysis-ansj#27]
`http://localhost:9200/docs/_analyze?text=ce%20shi&analyzer=index_ansj`
测试发现空格也被算作一个和token,要如何去掉这个?
 `{"tokens":[{"token":"ce","start_offset":0,"end_offset":2,"type":"en","position":0},{"token":" ","start_offset":2,"end_offset":3,"type":"null","position":1},{"token":"shi","start_offset":3,"end_offset":6,"type":"en","position":2}]}`

**Comment by suclogger** [comment]
在停用词中过滤即可。

**Comment by jack-nie** [comment]
@suclogger 试过了，貌似没用。。我再看下是不是哪里出问题了

**Comment by shi-yuan** [comment]
加停用词是可以的。先检查检查：
插件版本≥2.3.3.1
文件路径正确，并且文件编码是UTF-8

**Comment by jack-nie** [comment]
试了一下,还是不行,能除停用词,但是过滤不了空格

**Comment by shi-yuan** [comment]
[stopLibrary.TXT](https://github.com/NLPchina/elasticsearch-analysis-ansj/files/350129/stopLibrary.TXT)
插件版本为最新
topLibrary.dic（直接把后缀TXT改成dic）包含空格，中文的逗号，中文的逗号
测试http://localhost:9200/_cat/analyze?text=ce%20%20%20%20%20%20%20shi&analyzer=index_ansj，
结果：
`ce 		0		2 		0		en		
shi		9		12		1		en	`

没问题，可以过滤空格

**Comment by haochun** [comment]
尴尬，，我也遇到这个问题了，，，请问怎么解决的？


![image](https://user-images.githubusercontent.com/9320176/30208473-258014ac-94c6-11e7-86a8-df757e1004b7.png)

**Comment by shi-yuan** [comment]
[Issue#90](https://github.com/NLPchina/elasticsearch-analysis-ansj/issues/90)

**Comment by haochun** [comment]
...不行呀，，我把我的配置文件上传，还有词典也上传，一样的结果。空格还是不行。
我的es版本是5.5.2，插件是对应的版本。
![image](https://user-images.githubusercontent.com/9320176/30239272-454f359a-958b-11e7-8b06-6a873c54fa2a.png)


配置文件：
[ansj_library.zip](https://github.com/NLPchina/elasticsearch-analysis-ansj/files/1289693/ansj_library.zip)

![image](https://user-images.githubusercontent.com/9320176/30239274-4ee91ed6-958b-11e7-8570-18ced9eae7c0.png)

**Comment by shi-yuan** [comment]
@haochun 5.5.2，stop空格的话，得用正则了：
![image](https://user-images.githubusercontent.com/8057153/30245486-d4a3c2e2-960d-11e7-8704-198002c105f3.png)

**Comment by haochun** [comment]
@shi-yuan 能否给个样例停用词库?我测试了 \s+ regex 和\s+-regex 都不行，谢谢！

![image](https://user-images.githubusercontent.com/9320176/30255180-071296a6-96d4-11e7-924c-f06eb9a40427.png)

**Comment by haochun** [comment]
已经解决，感谢 @shi-yuan  还专门加qq，非常感谢。这里说明下情况，我使用的es版本是5.5.2，过滤空格的正确写法是：  \s+[TAB]regex  这中间是tab，不是空格，也不是-。

**Comment by zhmz1326** [comment]
![image](https://user-images.githubusercontent.com/285687/32480539-477b6cfe-c3ca-11e7-9051-0eeb095e9d69.png)
感谢大家。配置好后用的效果是这样的。

**Comment by iusofts** [comment]
傻傻的照着打了一遍   \s+[TAB]regex 原来[TAB] 是表示那个位置是个tab键
完整的是这样的“\s+	regex”

**Comment by shi-yuan** [comment]
@iusofts 对，中间是按制表符隔开的，不是空格符

**Comment by fujiahui** [comment]
\s+[TAB]regex 加入这个以后 需要重新reindex嘛？

**Comment by iusofts** [comment]
不用重新reindex 因为你query_index 的时候就把空格过滤掉的 不会作为查询条件了  但是需要重启一下ES

**Comment by fujiahui** [comment]
最后处理是加入两行还是一行
\s+[TAB]regex
 (空格)

**Comment by fujiahui** [comment]
\s+[TAB]regex
加入这个之后，也不起作用。版本你是6.4.1

**Comment by iusofts** [comment]
[TAB] 这个不是要直接写 ‘[TAB]’ 而是用键盘的tab键敲出来的

**Comment by fujiahui** [comment]
是的啊 我是用键盘直接敲的 木有起作用~~~~
