### ISSUE TITLE
分词的一个问题

### ISSUE THREAD

**Issue by suclogger** [NLPchina/elasticsearch-analysis-ansj#28]
添加了一些词条之后，出现一些问题：

通过`index_ansj`对`三打白骨精`进行分词：
![image](https://cloud.githubusercontent.com/assets/8472155/16790310/4f379422-48e7-11e6-97c6-811d9f09ef54.png)
没有最细粒度做分词

强制分词的结果数量好像有条数限制，容易出现数组越界。

**Comment by ansjsun** [comment]
http://demo.nlpcn.org/demo.jsp

你看索引分词的结果..是否是你要的.

强制分词?数组越界?能详细点吗

**Comment by shi-yuan** [comment]
关了哈，有问题再开吧
