### ISSUE TITLE
支持5.0.1有问题

### ISSUE THREAD

**Issue by libenyang** [NLPchina/elasticsearch-analysis-ansj#29]
5.0.1似乎接口改变比较多，插件支持不过

**Comment by shi-yuan** [comment]
最新插件已支持。新的配置，近期会加上

**Comment by libenyang** [comment]
非常感谢 @shi-yuan 等待新的插件

**Comment by shi-yuan** [comment]
最新版本，添加新的配置：
![image](https://cloud.githubusercontent.com/assets/8057153/17830458/28da816a-66fe-11e6-935b-d48df2c39683.png)
