### ISSUE TITLE
redis发布ambiguity及删除问题

### ISSUE THREAD

**Issue by yeyuelong** [NLPchina/elasticsearch-analysis-ansj#33]
1、执行redis命令：publish ansj_term a:c:减肥瘦身-减肥,nr,瘦身,v
在ambiguity.dic词典中会增加一行记录
减肥瘦身       减肥       nr          瘦身       v
而ansj_seg对于该词典的记录形式如：
李民     nr       工作     vn
三个      m       和尚      n
的确      d        定        v      不      v
大         a       和尚      n
它是双数的记录形式。
![image](https://cloud.githubusercontent.com/assets/20420441/18696405/67f2bf2e-7feb-11e6-999c-c23f92b2fdb9.png)
发现该处，导致在启动ES的时候会发现日志打印该信息
![image](https://cloud.githubusercontent.com/assets/20420441/18696435/bc67c3f6-7feb-11e6-8029-571ed60fb5b0.png)

2、执行redis命令：publish ansj_term a:d:减肥瘦身  会清空ambiguity.dic文档所有内容
![image](https://cloud.githubusercontent.com/assets/20420441/18696505/438cd2e0-7fec-11e6-8fad-eddad1d916d5.png)
用回之前的2.3.4版本的方法可以删除。
续：修正IO异常时导致的内存泄漏

**Comment by shi-yuan** [comment]
谢谢指出！

**Comment by yeyuelong** [comment]
然后就是我自己也加入了实现同义词词典的代码功能，希望请求合并，可以吗？
![image](https://cloud.githubusercontent.com/assets/20420441/18698233/0d9d7d9c-7ffb-11e6-998b-87eaaab163ef.png)

**Comment by shi-yuan** [comment]
可以

**Comment by yeyuelong** [comment]
您好，已申请提交pull request，烦请您合并，谢谢！

**Comment by shi-yuan** [comment]
嗯，这个插件依赖[ansj_seg](https://github.com/NLPchina/ansj_seg)

更新后，再合并哈

不好意思，您就耐心等待吧

**Comment by yeyuelong** [comment]
您好，ansj_seg已更新了，可以合并了；另，请问如果我想测试ambiguity.dic这个歧义词库是否应用上，该怎么测呢，怎么配置yml文件呢？

**Comment by shi-yuan** [comment]
恩知道了，谢谢提醒！

做这个配置：
![image](https://cloud.githubusercontent.com/assets/8057153/19633054/e9abc106-99df-11e6-8e0e-5cc79dfe1028.png)
这个目录配置了是相对config

然后
![image](https://cloud.githubusercontent.com/assets/8057153/19633072/1a6af776-99e0-11e6-9e8f-a5738bbcc7ce.png)

上面配置的文件里应该会有变化

**Comment by yeyuelong** [comment]
谢谢您的回复，您可能误会我的问题了，那个redis发布这块现在是没问题的^_^。
我是想知道elasticSearch这边要怎么应用上已知的用户库，比如歧义词的。举个例子吧：
这是我的ambiguity.dic歧义词库
![image](https://cloud.githubusercontent.com/assets/20420441/19635140/d104f704-99f2-11e6-99d5-113c25ae8218.png)
然后我对这段话执行分词：“邓超过生日玩动漫游戏”
![image](https://cloud.githubusercontent.com/assets/20420441/19635190/2498107c-99f3-11e6-8041-f863f26fa275.png)
最后它的分词结果是
![image](https://cloud.githubusercontent.com/assets/20420441/19635207/3f72aa60-99f3-11e6-8157-b4957d00c440.png)
![image](https://cloud.githubusercontent.com/assets/20420441/19635215/4a3f1f82-99f3-11e6-92a5-5449105489eb.png)
它分成了“超过”、“漫游”这样子，并没有按照我的ambiguity.dic歧义词库定义好的来分词，所以我是想知道该怎么让它用是我自定义的这个词库呢？elasticsearch.yml文件该怎么配置呢？
这个是我的yml配置文件：
![image](https://cloud.githubusercontent.com/assets/20420441/19635283/bf042e20-99f3-11e6-9c3c-461a8338045c.png)
再次您的感谢解答！

**Comment by shi-yuan** [comment]
测试版本：2.4.0，
http://localhost:9200/_analyze?analyzer=dic_ansj&text=邓超过生日玩动漫游戏
结果：
![image](https://cloud.githubusercontent.com/assets/8057153/19640269/80e21484-9a0e-11e6-9036-b2865e26ca10.png)

注意：
ambiguity.dic编码为UTF-8；
项之间用 \t 分隔；
重启试试

**Comment by shi-yuan** [comment]
请问这个是动态发布了，不起作用？如果是这样的话，可能是个bug

不好意思，会尽快处理的

**Comment by yeyuelong** [comment]
刚重启测试了一下分词没错，redis动态发布的可以，删除的不行。请问库的优先级是怎样的呢？能加下我QQ吗？726879048，多谢！

**Comment by shi-yuan** [comment]
请问，删除的不行，是删不了吗，还是删了不起作用？
库的优先级，是指？
