### ISSUE TITLE
词性使用问题

### ISSUE THREAD

**Issue by liaobs** [NLPchina/elasticsearch-analysis-ansj#35]
1. 索引分析阶段，通过ansj对文本进行了分词，会得到词性信息，想对不同的词性进行一些过滤（就像过滤停用词一样），请问如何做？
2. query查询阶段，query被分词后，每个term会有相应的词性，在排序的时候，不同的词性，可能对应的term weight不一样，所以在排序的时候需要用到词性信息，请问这个怎么做？
谢谢！

**Comment by shi-yuan** [comment]
可以看看[Keep Types Token Filter](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-keep-types-tokenfilter.html)

**Comment by shi-yuan** [comment]
是根据term的词性，来自定义排序？如果是这样，你得在排序的时候取到Term vectors，可以看看[Text scoring in scripts](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-advanced-scripting.html)

**Comment by liaobs** [comment]
检索的时候，词的词性信息怎样存储的，排序的时候有如何获得这个信息？谢谢

**Comment by liaobs** [comment]
是根据文档中的term词性进行排序的。

**Comment by shi-yuan** [comment]
索引的时候，可以单独加一个字段存储词性，或者可以使用payload来区分

**Comment by shi-yuan** [comment]
也可以写[native-java-scripts](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting.html#native-java-scripts)，根据term得到词性，给每个词性一个分值，实现排序
