### ISSUE TITLE
支持 ElasticSearch 5.0

### ISSUE THREAD

**Issue by rkq** [NLPchina/elasticsearch-analysis-ansj#38]
ElasticSearch 5.0出来了，搞下支持下吧！！！

**Comment by shi-yuan** [comment]
谢谢提醒，近期会加上

**Comment by shi-yuan** [comment]
ansj的配置没变，只不过得单独放在

$ES_HOME/config/analysis-ansj/ansj.cfg.yml  
或者
$ES_HOME/plugins/elasticsearch-analysis-ansj-*/config/ansj.cfg.yml
