### ISSUE TITLE
支持远程分词库吗,类似ik

### ISSUE THREAD

**Issue by fangstao** [NLPchina/elasticsearch-analysis-ansj#39]
https://github.com/medcl/elasticsearch-analysis-ik

**Comment by shi-yuan** [comment]
目前的热词更新，是通过Redis Pub/Sub实现的

**Comment by ansjsun** [comment]
这个即将支持,目前还在测试版本中..会在5.1.0中出现...感谢你的提议

**Comment by fangstao** [comment]
这样的话,es集群就可以共用同一个分词库了,不需要把分词库文件拷贝到每一个集群下面,不用拷贝文件就可以自动更新分词库,实现集中式管理分词库

**Comment by shi-yuan** [comment]
这个现在已经支持了，访问接口/_ansj/flush/dic

**Comment by buaanie** [comment]
请问下具体怎么使用呀？感觉还是不太明白 @shi-yuan

**Comment by pzhen** [comment]
@shi-yuan 

我的插件2.3.3 es也是2.3.3  我访问http://127.0.0.1:9200/_ansj/flush/dic  
es报错是没有索引：
```
{
error: {
root_cause: [
{
type: "index_not_found_exception",
reason: "no such index",
resource.type: "index_expression",
resource.id: "_ansj",
index: "_ansj"
}
],
type: "index_not_found_exception",
reason: "no such index",
resource.type: "index_expression",
resource.id: "_ansj",
index: "_ansj"
},
status: 404
}
```

**Comment by shi-yuan** [comment]
不好意思哈，[2.4.2或5.2.0以上](https://github.com/NLPchina/elasticsearch-analysis-ansj#242或520以上)才支持刷新接口的哦

**Comment by pzhen** [comment]
@shi-yuan 非常感谢！
