### ISSUE TITLE
想对插件做些修改，怎么把插件源码和es进行集成测试呢

### ISSUE THREAD

**Issue by hotchwong** [NLPchina/elasticsearch-analysis-ansj#40]

**Comment by shi-yuan** [comment]
可以写ESTestCase，进行测试

**Comment by shi-yuan** [comment]
可以看看[Testing](https://www.elastic.co/guide/en/elasticsearch/reference/current/testing.html)

**Comment by hotchwong** [comment]
IDE用intellij ,现在是把es和ansj插件都下载下来，es可以单独启动，ansj插件不知道怎么放到es里，按maven模块做了依赖，也是没起来，提示es依赖的jar找不到类，劳烦指导下
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/cli/CommandLineParser

**Comment by shi-yuan** [comment]
您是用intellij直接run的[elasticsearch](https://github.com/elastic/elasticsearch)，没起来，报的这个错吗？

**Comment by hotchwong** [comment]
嗯，把插件做为子模块了，我把代码都拷到es里直接运行，现在可以了。
ps：我是想实现分词的时候每个用户都用自己的用户字典进行分词，看插件代码没找到入口，这个是需要改es源码，还是ansj插件这块就可解决呢？

**Comment by ansjsun** [comment]
同问

发自我的 iPhone

**Comment by shi-yuan** [comment]
每个用户都用自己的用户字典进行分词，意思是配置不同分析器，每个分词器加载自己的词典吗?

目前，插件配置的词典是全局生效的，暂不支持配置不同分析器，每个分词器加载自己的词典

**Comment by ansjsun** [comment]
这个需求也是咱们的需求之一！

所以要做 思考题！ 不难


发自我的 iPhone
