### ISSUE TITLE
index_ansj分词疑惑

### ISSUE THREAD

**Issue by hrdxwandg** [NLPchina/elasticsearch-analysis-ansj#42]
使用index_ansj模式进行分词。会把单字也切分出来。拿作者的例子“六味地黄丸软胶囊“。切分结果中包含了"六、味、地、黄、丸、软、胶、囊"，与作者描述的不一致。

**Comment by gitxxx** [comment]
可能你配置的ansj插件没有生效

**Comment by adonis2014** [comment]
@hrdxwandg  我也发现了这个问题。index_ansj 感觉包含了单字分词，和作者测试例子确实不一样，不知道什么问题。

**Comment by ansjsun** [comment]
你们打开自定义词典..就是 default.dic 词典.把里面的单字删掉..就可以了...


是因为index分词方式是基于..词典来决定显示哪些词语的

**Comment by adonis2014** [comment]
谢谢ansjsun回复。将配置修改成
![image](https://cloud.githubusercontent.com/assets/8855523/20960054/6a1685f2-bc99-11e6-871a-16740708a00c.png)
enabled_stop_filter: false
enable_skip_user_define: true
就可以了。

**Comment by hrdxwandg** [comment]
@adonis2014 
你的这个方法对“六味地黄丸软胶囊” OK。
但是如果对“中华人民共和国”进行分词，只能分出“中华人民共和国”和“人民共和国”两种了。

**Comment by ansjsun** [comment]
@hrdxwandg   enable_skip_user_define: true
   这个去掉...

**Comment by hrdxwandg** [comment]
@ansjsun 去掉enable_skip_user_define: true也不行。

**Comment by HappyBeer** [comment]
5.0.2 版本 同样的问题， 也不行，该怎么配置呢

**Comment by ansjsun** [comment]
吧用户自定义词典的单字去掉..应该在default.dic里面...
