### ISSUE TITLE
歧义字典的问题

### ISSUE THREAD

**Issue by ljp001** [NLPchina/elasticsearch-analysis-ansj#48]
怎么避免index_ansj分词方式中，不将歧义字典中的词再次分开，  歧义字典中有个 不确定  但是分词结果中既有 不确定，也有    确定   。。。 设置了enable_skip_user_define: false

**Comment by Andq00** [comment]
额,是我不太会用歧义字典么,   人民法院  总是被查分为  人民   民法   法院   怎么避免民法这个词的

**Comment by ansjsun** [comment]
不用index方式分词..才能保证人民法院不被拆开.用toanalysis方式试试
