### ISSUE TITLE
高亮 混乱问题

### ISSUE THREAD

**Issue by 541079843** [NLPchina/elasticsearch-analysis-ansj#49]
使用的是2.3.4版本，中文文章中包含都种标点符号，使用fvh方式显示高亮，获得的高亮却总是混乱，与输入关键词无关，应该是分词索引position错乱了，尝试过滤标点符号，依然失败。

**Comment by ansjsun** [comment]
fvh高亮的方式没用过..一般高亮是因为/r 引起的..你尝试replace /r  如果还有..发给我看看....
