### ISSUE TITLE
ES 1.7.2 按 1.x 版本指令安装后不能使用

### ISSUE THREAD

**Issue by rkq** [NLPchina/elasticsearch-analysis-ansj#51]
ES 1.7.2 按 1.x 版本指令安装后不能使用，运行：

curl '127.0.0.1:9200/_analyze?analyzer=query_ansj' -d '中华人民共和国'

出现下列错误：

{"error":"ElasticsearchIllegalArgumentException[failed to find analyzer [query_ansj]]","status":400}

换成 search_ansj，index_ansj 也报同样的错误。

**Comment by shi-yuan** [comment]
创建测试索引：
```
curl -XPUT 127.0.0.1:9200/test -d '{
    "settings" : {
        "number_of_shards" : 1,
        "number_of_replicas" : 0

    },
    "mappings" : {
        "test" : {
            "_all" : { "enabled" : false },
            "properties" : {
                "name" : { "type" : "string", "analyzer" : "ansj_index" }
            }
        }
    }
}'
```

添加索引内容：
```
curl -XPUT 'http://127.0.0.1:9200/test/test/1' -d '{
    "name" : "中国人民万岁",
    "post_date" : "2009-11-15T14:12:12",
    "message" : "trying out Elasticsearch"
}'
```

测试：
http://127.0.0.1:9200/test/_analyze?analyzer=ansj_index&text=中国人民
http://127.0.0.1:9200/test/_analyze?analyzer=ansj_query&text=中国人民
http://127.0.0.1:9200/test/_analyze?tokenizer=ansj_index_token&text=中国人民
http://127.0.0.1:9200/test/_analyze?tokenizer=ansj_query_token&text=中国人民

**Comment by rkq** [comment]
原来 ES 1.x 版本必须要创建 index 才能调这个接口，不像高版本。非常感谢！
