### ISSUE TITLE
5.1.1 URL不存在

### ISSUE THREAD

**Issue by zzvv** [NLPchina/elasticsearch-analysis-ansj#52]
貌似最高版本只有5.0.1

**Comment by shi-yuan** [comment]
谢谢提醒，已发布 [elasticsearch-analysis-ansj-5.1.1.0-release.zip](https://github.com/NLPchina/elasticsearch-analysis-ansj/releases/download/5.1.1.0/elasticsearch-analysis-ansj-5.1.1.0-release.zip)
