### ISSUE TITLE
MD5 Hash字符串被分词

### ISSUE THREAD

**Issue by rkq** [NLPchina/elasticsearch-analysis-ansj#53]
Elasticsearch 1.7.2
ansj 插件 1.x 版本

类型 string，未指定 not_analyze，  值 fd04fe9b5225461204e75837f1616575，  分词器  index_ansj 

该值被分词结果如下：

{'tokens': [{'end_offset': 2,
   'position': 1,
   'start_offset': 0,
   'token': 'fd',
   'type': 'word'},
  {'end_offset': 4,
   'position': 2,
   'start_offset': 2,
   'token': '04',
   'type': 'word'},
  {'end_offset': 6,
   'position': 3,
   'start_offset': 4,
   'token': 'fe',
   'type': 'word'},
  {'end_offset': 7,
   'position': 4,
   'start_offset': 6,
   'token': '9',
   'type': 'word'},
  {'end_offset': 8,
   'position': 5,
   'start_offset': 7,
   'token': 'b',
   'type': 'word'},
  {'end_offset': 18,
   'position': 6,
   'start_offset': 8,
   'token': '5225461204',
   'type': 'word'},
  {'end_offset': 19,
   'position': 7,
   'start_offset': 18,
   'token': 'e',
   'type': 'word'},
  {'end_offset': 24,
   'position': 8,
   'start_offset': 19,
   'token': '75837',
   'type': 'word'},
  {'end_offset': 25,
   'position': 9,
   'start_offset': 24,
   'token': 'f',
   'type': 'word'},
  {'end_offset': 32,
   'position': 10,
   'start_offset': 25,
   'token': '1616575',
   'type': 'word'}]}

请问这样分词的依据是什么啊？谢谢！

**Comment by ansjsun** [comment]
数字和英文分开的呀...md5 分词器应该选择keyword
