### ISSUE TITLE
有几个关于配置上的小问题请教一下

### ISSUE THREAD

**Issue by NicolJiang** [NLPchina/elasticsearch-analysis-ansj#55]
如果有详细的说明文档了，还请告诉我一下，因为找了很久都没找到。。。

1. redis远程push的方式，有具体的命令说明吗？

2. 我想用来管理默认词典、停用词典 等，应该如何配置？

3. 同义词词典怎么配置？

4. ansj会把标点符号，甚至是空格都保留下来，这对兼容.Net、C++、C#等词很有用，但很多无用的符号，要怎么处理呢，当作停用词放到停用词典里？

5. 除在http://maven.nlpcn.org/down/library/ 中看到「ambiguity.dic」之外，其他词典都没找到范例，不知能否告知一下在哪了解？

**Comment by shi-yuan** [comment]
1. redis publish 
2. [全局配置](https://github.com/NLPchina/elasticsearch-analysis-ansj#分词文件配置)
3. 同义词词典的配置，得依赖插件的版本
4. 可以放在停用词典里
5. [词典范例](https://github.com/NLPchina/ansj_seg/tree/master/library)

**Comment by markisme** [comment]
ansj配置文件中词典目录路径是相对配置文件位置的相对路径吗？

**Comment by shi-yuan** [comment]
也可以写绝对路径

**Comment by markisme** [comment]
👌 @shi-yuan
