### ISSUE TITLE
我使用的是elasticsearch的2.4.4版本，没有对应版本的插件，我使用2.4.1的对应插件会有问题吗？

### ISSUE THREAD

**Issue by luciuschina** [NLPchina/elasticsearch-analysis-ansj#56]
我使用的是elasticsearch的2.4.4版本，没有对应版本的插件，我使用2.4.1的对应插件会有问题吗？

**Comment by shi-yuan** [comment]
需要把pom.xml里的elasticsearch.version改成2.4.4，然后重新打包

**Comment by luciuschina** [comment]
恩，我选了个2.4.2版本 改了pom.xml后重新编译可以的
