### ISSUE TITLE
[邓超过生日玩动漫游戏] 分词疑惑

### ISSUE THREAD

**Issue by NicolJiang** [NLPchina/elasticsearch-analysis-ansj#57]
如图...
1、邓超过 问题（如图1）：
歧义词典中有「邓超 n 过 v 生日 n」，但search_ansj仍然分成了「邓 超过」。
<img width="1000" alt="qq20170317-014058 2x" src="https://cloud.githubusercontent.com/assets/16457655/24010425/cfdbd5ba-0ab2-11e7-9c8d-ff1794aa42aa.png">

2、动漫游 问题（如图2）：
词库里有「动漫」「游戏」「动漫游」「漫游」「动漫游戏」，歧义词典中还有「动漫 n 游戏 n」
index_ansj 为何将「动漫」「动漫游」分出来了，但「游戏」「漫游」没有呢（虽然 漫游 不应该分出来）？
<img width="865" alt="qq20170317-012614 2x" src="https://cloud.githubusercontent.com/assets/16457655/24009737/db9cfe9e-0ab0-11e7-978d-74abb4745853.png">

**Comment by NicolJiang** [comment]
对了，并且，歧义词典中还有：

动漫    n       游戏    n

**Comment by ansjsun** [comment]
1.你分词插件的版本是?
2.如果是最新版.用dic方式做查询的分词.

**Comment by NicolJiang** [comment]
都是5.1.2。
用dic方式做查询的分词是啥意思？
感谢回复～

**Comment by NicolJiang** [comment]
问题已解决，将「enable_skip_user_define」设置成false。
