### ISSUE TITLE
请问 index_ansj 似乎没有生效？

### ISSUE THREAD

**Issue by RaicmL** [NLPchina/elasticsearch-analysis-ansj#69]
curl -XGET host:9200/_analyze?analyzer=index_ansj -d '旅游地'

{"tokens":[{"token":"旅游地","start_offset":0,"end_offset":3,"type":"n","position":1}]}

切分的结果只有'旅游地'一个token。记得很早以前当时用2.3版本的时候,是可以分出更小粒度的。

做了一些别的测试，发现index-ansj和query-ansj是一样的。请问是什么原因？

谢谢~

**Comment by shi-yuan** [comment]
@ansjsun 旧版可以分出：
```json
{
tokens: [
{
token: "旅游地",
start_offset: 0,
end_offset: 3,
type: "word",
position: 0
},
{
token: "旅游",
start_offset: 0,
end_offset: 2,
type: "word",
position: 1
}
]
}
```

**Comment by shi-yuan** [comment]
更细粒度的话，需要添加词典

**Comment by xljhtq** [comment]
@shi-yuan 请问我想要在本地单独做“ index_ansj“模式的分词，这个怎么处理呢？

**Comment by shi-yuan** [comment]
直接用ansj_seg的包进行“ index_ansj“模式的分词？
