### ISSUE TITLE
安装 x-pack 后，执行http://172.17.220.73:9200/_cat/ansj/config 报错

### ISSUE THREAD

**Issue by adonis2014** [NLPchina/elasticsearch-analysis-ansj#76]
http://172.17.220.73:9200/_cat/ansj/config
`{
error: - {
root_cause: - [
- {
type: "security_exception",
reason: "action [ansj:analyze] is unauthorized for user [elastic]"
}
],
type: "security_exception",
reason: "action [ansj:analyze] is unauthorized for user [elastic]"
},
status: 403
}`

**Comment by shi-yuan** [comment]
未授权吧？

**Comment by shi-yuan** [comment]
[开启xpack的权限认证后，ansj的api报未授权](https://github.com/NLPchina/elasticsearch-analysis-ansj/issues/105)
