### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by ytcpub** [NLPchina/elasticsearch-analysis-ansj#80]
下载到本地后 执行安装，报如下错误:
sudo bin/elasticsearch-plugin install ./elasticsearch-analysis-ansj-5.4.0.0-release.zip
A tool for managing installed elasticsearch plugins

Commands
--------
list - Lists installed elasticsearch plugins
install - Install a plugin
remove - removes a plugin from Elasticsearch

Non-option arguments:
command              

Option         Description        
------         -----------        
-h, --help     show help          
-s, --silent   show minimal output
-v, --verbose  show verbose output
ERROR: Unknown plugin ./elasticsearch-analysis-ansj-5.4.0.0-release.zip

**Comment by geekidentity** [comment]
还没解决
