### ISSUE TITLE
是否可以让ansj在elasticsearch的一个字段里进行如下拆分?

### ISSUE THREAD

**Issue by bigfanofcpp** [NLPchina/elasticsearch-analysis-ansj#81]
一次性分词,除了按照ansj默认的方式拆分,还能按照单个字拆分?不使用multi-fields形式
比如: 北京宇猫科技公司, 也就是拆分成: 北京,宇猫,科技,公司,北,京,宇,猫,科,技,公,司

**Comment by shi-yuan** [comment]
应该是不行的，除非自己修改ansj_lucene插件

**Comment by shi-yuan** [comment]
还有一种办法，就是，给分词器添加一个词典，词典里包含这些单字。这样的话，是能分出来的
