### ISSUE TITLE
如何在创建索引时指定自定义的关键词、停用词等库

### ISSUE THREAD

**Issue by geekidentity** [NLPchina/elasticsearch-analysis-ansj#83]
使用如下方式创建一个索引，如何在创建索引时指定自定义的关键词、停用词等库（不同的索引要有不同的库），么么哒。
curl -XPUT localhost:9200/cdr_3000002?pretty -d'{
"settings": {
                "number_of_shards": 1,
                "number_of_replicas": 1,
                "max_result_window": 100000,
                "analysis": {
                        "analyzer": {
                                "cdr_3000002": {
                                        "type": "custom",
                                        "stop_path": "library/stop3000002.dic",
                                        "tokenizer": "dic_ansj"
                                }
                        }
                }
        }

}'

**Comment by shi-yuan** [comment]
```json
{
  "settings": {
    "index": {
      "analysis": {
        "tokenizer": {
          "my_dic": {
            "type": "dic_ansj",
            "dic": "dicKey",
            "stop": "stopKey"
          }
        },
        "analyzer": {
          "my_dic": {
            "type": "custom",
            "tokenizer": "my_dic"
          }
        }
      }
    }
  }
}
```

**Comment by geekidentity** [comment]
现在就是这样做的，但使用curl -XGET 'localhost:9200/cdr_3000002/_analyze 并指定analyzer为my_dic 进行分词时ES有警告
WARN ][o.a.l.DicLibrary         ] dic dicKey not found in config 
这是什么原因。

如果将tokenizer中的"dic": "dicKey"改为"dic_xxx": "dicKey",不会出现该警告，但词库不会生效，从代码中看好像只能是"dic": "dicKey"这样设置

**Comment by shi-yuan** [comment]
dicKey，是需要在[ansj的配置](https://github.com/NLPchina/elasticsearch-analysis-ansj#分词文件配置)里配置的
