### ISSUE TITLE
忽略量词

### ISSUE THREAD

**Issue by jqwang** [NLPchina/elasticsearch-analysis-ansj#84]
是否有相关配置可以在搜索时忽略“五次”，“10月”，“20日”等词（除了全部遍历后放到停用词中）

**Comment by shi-yuan** [comment]
没有配置。
针对这种情况，可以考虑，自定义一个分词器，加一个量词的Recognition，搜索的时候将量词过滤掉。
具体实现，可以参考[StopRecognition](https://github.com/NLPchina/ansj_seg/blob/master/src/main/java/org/ansj/recognition/impl/StopRecognition.java)
