### ISSUE TITLE
index_ansj和query_ansj返回的结果一样？

### ISSUE THREAD

**Issue by zxspopo** [NLPchina/elasticsearch-analysis-ansj#88]
你好，我使用的是2.4.2版本。
http://localhost:9200/_cat/test/analyze?text=%E5%85%AD%E5%91%B3%E5%9C%B0%E9%BB%84%E4%B8%B8%E8%BD%AF%E8%83%B6%E5%9B%8A&analyzer=index_ansj

六味 		0		2		0		m 		
地  		2		3		1		uv		
黄丸软		3		6		2		nr		
胶囊 		6		8		3		n

**Comment by shi-yuan** [comment]
没加词典
