### ISSUE TITLE
elasticsearch下分词能分出来，但是检索不出来

### ISSUE THREAD

**Issue by zhaoweijing2003** [NLPchina/elasticsearch-analysis-ansj#96]
分词结果："起动"可以分词出来，
![default](https://user-images.githubusercontent.com/5343500/33166881-bd726b8e-d076-11e7-9a87-100a7fb26c2d.png)

但是用"起动"检索不到：
![default](https://user-images.githubusercontent.com/5343500/33166890-c10578c2-d076-11e7-9cd9-fd4c67b9ca3e.png)

**Comment by ansjsun** [comment]
把动起这个词语加到自定义词典中尝试是否能搜索到。


可能因为query中的动起被拆开了



在 2017-11-23 17:50:18，"zhaoweijing2003" <notifications@github.com> 写道：


分词结果："起动"可以分词出来，


但是用"起动"检索不到：

**Comment by zhaoweijing2003** [comment]
我在创建mapping的时候，analyzed,search_analyzed都是index_ansj。所以比较奇怪，是不是不能都设置为index_ansj

**Comment by ansjsun** [comment]
可以都能设置为index_ansj.

你用这个mapping的分词单独分一下动起看看结果是什么

**Comment by zhaoweijing2003** [comment]
GET _analyze               
{
 "text": "起动",
 "analyzer": "index_ansj"
}
结果：
{
  "tokens": [
    {
      "token": "起",
      "start_offset": 0,
      "end_offset": 1,
      "type": "vf",
      "position": 1
    }
  ]
}

**Comment by zhaoweijing2003** [comment]
添加了两个词，起 和 动，重新索引，问题解决了。谢谢 @ansjsun

**Comment by ansjsun** [comment]
@zhaoweijing2003 动是停用词吗 ？？怎么没分出来
