### ISSUE TITLE
es6.0 什么时候可以支持呢？

### ISSUE THREAD

**Issue by kinbod** [NLPchina/elasticsearch-analysis-ansj#97]
when can we use this plugin with es6.0 ?? thx for your hardworking..

**Comment by shi-yuan** [comment]
Stay tuned !

**Comment by shi-yuan** [comment]
[支持es6.0.0版本的分词插件](https://github.com/NLPchina/elasticsearch-analysis-ansj/releases/tag/v6.0.0)
