### ISSUE TITLE
热更新失败

### ISSUE THREAD

**Issue by pzhen** [NLPchina/elasticsearch-analysis-ansj#99]
我的插件2.3.3 es也是2.3.3 我访问http://127.0.0.1:9200/_ansj/flush/dic
es报错是没有索引：

{
error: {
root_cause: [
{
type: "index_not_found_exception",
reason: "no such index",
resource.type: "index_expression",
resource.id: "_ansj",
index: "_ansj"
}
],
type: "index_not_found_exception",
reason: "no such index",
resource.type: "index_expression",
resource.id: "_ansj",
index: "_ansj"
},
status: 404
}
麻烦帮忙看下 谢谢

**Comment by shi-yuan** [comment]
不好意思哈，[2.4.2或5.2.0以上](https://github.com/NLPchina/elasticsearch-analysis-ansj#242或520以上)才支持刷新接口的哦
